config/routes.rb
Rails.application.routes.draw do

  get 'qiniu/uptoken'
  post 'qiniu/private_url'

  root 'admin/sessions#new'
  get 'sms/captcha', to: 'sms#captcha'

  namespace :admin do
    root 'main#index'

    #商城支付
    get 'shop_detail/index'
    get 'shop_detail/go_to_alipay_pc_direct_pay'
    
    get 'shop_buy/index'
    get 'shop_buy/pingpp_alipay_pc_dirct_payment' 
    

    #分店的首页
    resources :branchs

    namespace :targets do
      #意向学员分配
      resources :potential_students do
        member do
        get 'assign'
        end
        collection do
        end
      end
      #学员分配
      resources :students do
        member do
          get 'assign'
        end
      end
    end


    #用户注册
    resources :users do
      collection do
        get 'search_user_by_mobile'
        get 'user_present_or_not'
        get 'sign_up', to: "users#new"
        get 'phone', to: "users#new"
        get 'email', to: "users#email"
        get 'change_pwd', to: 'users#change_pwd'
        post 'change_pwd', to: "users#update_pwd"
      end
    end


    #用户登录与退出
    resources :sessions do
      collection do
        get "sign_in", to: "sessions#new"
        post 'sign_in', to: "sessions#create"
        get "authoriz_failed", to: "sessions#authoriz_failed"
        get :logout
      end
    end

    #固定成本设置
    resources :fixed_costs do
    end

    #分店内的数据统计
    resources :statistics do
      collection do
        get "comprehensive"
        get "commodity"
        get "curriculum"
        get "recruit"
        get "service"
        get "student"
        get "teacher"
      end
    end

    #公司那边的数据统计
    resources :statistical_datum do
      collection do
        #综合统计
        get "comprehensive"
        get "change_comprehensive"
        get "commodity"
        get "change_commodity"
        get "curriculum"
        get "change_curriculum"
        get "recruit"
        get "service"
        get "student"
        get "change_student"
        get "teacher"
        get "change_teacher"
        get "finance"
        get "resource"
      end

    end

    #服务顾问服务系统
    resources :service_consultants do

    end

    #指标的设置
    resources :targets do
      collection do
        #---- 总监指标 ----
        get 'director'
        get 'director_target'
        get 'new_director_target'
        post 'save_director_target'
        get 'edit_director_target'
        post 'update_director_target'
        #---- end -----
        #----- 市场专员 ------
        get 'market'
        get 'market_target'
        get 'new_market_target'
        post 'save_market_target'
        get 'edit_market_target'
        post 'update_market_target'
        get 'detail_market'
        get "get_market_detail_list"
        get 'assign_potential_students'
        #---------- end ----------
        #---------服务顾问--------
        get 'operator'
        get 'operator_target'
        get 'new_operator_target'
        post 'save_operator_target'
        get 'edit_operator_target'
        post 'update_operator_target'
        get 'detail_operator'
        get "get_operator_detail_list"
        #----------- end ----------
        #---------导师指标---------
        get 'teacher'
        get 'teacher_target'
        get 'new_teacher_target'
        post 'save_teacher_target'
        get 'edit_teacher_target'
        post 'update_teacher_target'
        get 'detail_teacher'
        #----------- end ----------

      end
    end

    #学员系统
    resources :students  do
      #评价或回访
      resources :student_remarks do
        collection do
          get "get_data_list"
        end
      end
      member do
        get "orders"
      end
      collection do
        post "save_student"
        get "get_student_list"
      end
    end

    #课程周表
    resources :course_weeks do
      member do
        get "appointment"
        get "student_check"
        get "teacher_check"
      end
      collection do
        get "get_course_week"
        post "check_in"
        get "new_private_check_in"
        post "private_check_in"
        post "teacher_check_in"
        post "appointmented"
        get "get_pay_way"
        delete "destroy_appointment_record"
      end
    end

    #课程设置
    resources :course_infos do
      member do
        delete "close_course"
      end
      collection do
        get "get_course_list"
        post "update_course"
        delete "destroy_appointment_record"
      end
    end

    #意向学员
    resources :potential_students do
      collection do
        get "new_remark"
        post "save_remark"
        get "check_student"
        post "save_student"
        get "get_student_list"
      end
    end

    #财务
    resources :finances do
      member do
        get 'edit_income'
        get 'edit_expense'
      end
      collection do
        get "laborage"
        get 'initial_state'
        post 'set_initial'
        get 'income'
        get 'expense'
        get "get_finance_list"
        get 'month_expenditure'
      end
    end

    # 商品
    resources :goods do
      member do
        get :record
        get :change_status
        get :price
        post :update_good
      end
      collection do
        get :goods_shop
        get :get_good_list
        get :new_order
        post :create_order
      end
    end

    # 导师系统
    resources :teachers do
      member do
        get :get_course_week
        get :get_course_week_detail
      end
      collection do
        get :get_teacher_search_out
        get :get_teacher_by_name_phone
        get :get_my_students_by_teacher_id
        get :get_my_record_teaching_salary
        get :get_my_students_by_teacher_id
        get :show_my_student_detail
        get :remark_my_student
        get :new_comment_in_teacher
      end
    end

    # 订单
    resources :orders do
    end

    # 公司
    resources :companies do
      collection do
        get :recharge
        get :new_studio
        get :finish_paying
        get :switch_company
      end
    end

    # 员工
    resources :employees do
      collection do
        get 'get_employee'
      end
    end

    # 分店
    resources :studios do
      collection do
        get :finish_paying
        get :switch_studio
        get :update_studio_name
      end
    end

    # 公司设置
    resources :company_configurations do
      collection do
        #删除公司设置
        delete :destroy_configuration
        delete :destroy_goods_category

        #学员设置
        get :student
        post :create_student_group
        post :create_potential_student_group

        #课程设置
        get :course
        post :create_course_room
        post :update_private_education

        #商品设置
        get :goods
        post :create_goods_category

        #人资设置
        get :employee
        post :create_department
        post :create_position
        post :create_teacher_level
        post :create_employee_welfare

        #奖金设置
        get :bonus
        post :update_company_name
        post :update_bonus
      end
    end

  end
end

app/controllers/admin/company_configurations_controller.rb
# 公司设置
class Admin::CompanyConfigurationsController < Admin::ApplicationController
  layout "admin"
  before_action :set_current_company
  #before_action :set_current_company, only: [:show, :edit, :update, :destroy]

  #删除公司设置
  def destroy_configuration
    if ['StudentGroupConfiguration', 'PotentialStudentGroupConfiguration', 'DepartmentConfiguration', 'PositionConfiguration', 'TeacherLevelConfiguration', 'EmployeeWelfareConfiguration', 'CourseRoomConfiguration'].include?params[:model_name]
      Object.const_get(params[:model_name]).destroy(params[:value])
    end
    render :text => 'ok'
  end

####  学员设置 ####
  def index
    @current_company = current_company
    @groups = @current_company.student_group_configurations
    @group = StudentGroupConfiguration.new()
    #@potential_groups = @current_company.potential_student_group_configurations
    #@potential_group= PotentialStudentGroupConfiguration.new()
  end

  #新增学员分组
  def create_student_group
    group = StudentGroupConfiguration.new(student_group_configuration_params)
    group.company_id = @current_company.id
    group.save!
    redirect_to admin_company_configurations_path
  end

  #新增意向学员分组
  #def create_potential_student_group
  #  potential_group = PotentialStudentGroupConfiguration.new(potential_student_group_configuration_params)
  #  potential_group.company_id = @current_company.id
  #  potential_group.save!
  #  redirect_to admin_company_configurations_path,:notice =>  "新增学员分组成功"
  #end

#### 课程设置 ####
  def course
    @course_rooms = @current_company.course_room_configurations
    @course_room = CourseRoomConfiguration.new()
    @current_studios = Studio.where(company_id: @current_company.id)
    @private_education = @current_company.private_education_configuration
    unless @private_education
      @private_education = PrivateEducationConfiguration.new
    end
  end

  #新增舞蹈教室
  def create_course_room
    course_room = CourseRoomConfiguration.new(course_room_params)
    course_room.company_id = @current_company.id
    course_room.save!
    redirect_to course_admin_company_configurations_path(tp: 'course')
  end

  #保存私教设置
  def update_private_education
    @private_education = @current_company.private_education_configuration
    if @private_education.present?
      @private_education.duration = private_education_params[:duration]
    else
      @private_education = PrivateEducationConfiguration.new(private_education_params)
      @private_education.company_id = @current_company.id
    end
    @private_education.save!
    redirect_to course_admin_company_configurations_path(tp: 'course')
  end

#### 商品设置 ####
  def goods
    goods_categories = @current_company.sale_courses.where(sale_type: '周边商品')
    @private_goods = goods_categories.privates
    @default_goods = goods_categories.defaults
    @goods_category = SaleCourse.new()
  end

  #新增商品分类
  def create_goods_category
    goods_category = SaleCourse.new(goods_category_params)
    goods_category.company_id = @current_company.id
    goods_category.sale_type = '周边商品'
    goods_category.save!
    redirect_to goods_admin_company_configurations_path(tp: 'goods')
  end

  #删除商品分类
  def destroy_goods_category
    goods_category = SaleCourse.find(params[:value])
    goods_category.destroy
  end

#### 人资设置 ####
  def employee
    @default_departments= @current_company.department_configurations.defaults
    @private_departments= @current_company.department_configurations.privates
    @department = DepartmentConfiguration.new()
    @default_positions= @current_company.position_configurations.defaults
    @private_positions= @current_company.position_configurations.privates
    @position = PositionConfiguration.new()
    @teacher_levels= @current_company.teacher_level_configurations
    @teacher_level = TeacherLevelConfiguration.new()
    @employee_welfares= @current_company.employee_welfare_configurations
    @employee_welfare = EmployeeWelfareConfiguration.new()
  end

  #新增自定义部门
  def create_department
    department = DepartmentConfiguration.new(department_configuration_params)
    department.company_id = @current_company.id
    department.save!
    redirect_to employee_admin_company_configurations_path(tp: 'employee')
  end

  #新增自定义职位
  def create_position
    position = PositionConfiguration.new(position_configuration_params)
    position.company_id = @current_company.id
    position.save!
    redirect_to employee_admin_company_configurations_path(tp: 'employee')
  end

  #新增导师等级
  def create_teacher_level
    teacher_level = TeacherLevelConfiguration.new(teacher_level_configuration_params)
    teacher_level.company_id = @current_company.id
    teacher_level.save!
    redirect_to employee_admin_company_configurations_path(tp: 'employee')
  end

  #新增员工福利
  def create_employee_welfare
    employee_welfare = EmployeeWelfareConfiguration.new(employee_welfare_configuration_params)
    employee_welfare.company_id = current_company.id
    employee_welfare.save!
    #respond_to do |format|
    #  format.js
    #end
    redirect_to employee_admin_company_configurations_path(tp: 'employee')
  end

#### 奖金设置 ####
  def bonus
    @bonus = @current_company.bonus_configuration
    unless @bonus
      @bonus = BonusConfiguration.new
    end
  end

  #修改公司名称
  def update_company_name
    @current_company = @current_company
    @current_company.update(name: params[:company][:name])
    @current_company.save!
    redirect_to bonus_admin_company_configurations_path(tp: 'bonus')
  end

  # 保存奖金设置
  def update_bonus
    @bonus = @current_company.bonus_configuration
    # 启用奖金池
    if params[:open] == "1"
      if @bonus.present?
        @bonus.update(bonus_percent: bonus_params[:bonus_percent], one_month_sale: bonus_params[:one_month_sale], total_sale: bonus_params[:total_sale])
      else
        @bonus = BonusConfiguration.new(bonus_params)
        @bonus.company_id = @current_company.id
        @bonus.save!
      end
    # 关闭奖金池
    else
      @bonus.destroy if @bonus.present?
    end
    redirect_to bonus_admin_company_configurations_path(tp: 'bonus')
  end

  private
    def set_current_company
      @current_company = current_company
    end
    def student_group_configuration_params
      params.require(:student_group_configuration).permit(:company_id, :group_name)
    end
    def potential_student_group_configuration_params
      params.require(:potential_student_group_configuration).permit(:company_id, :group_name)
    end
    def department_configuration_params
      params.require(:department_configuration).permit(:company_id, :department_name)
    end
    def position_configuration_params
      params.require(:position_configuration).permit(:company_id, :position_name)
    end
    def teacher_level_configuration_params
      params.require(:teacher_level_configuration).permit(:company_id, :teacher_level)
    end
    def employee_welfare_configuration_params
      params.require(:employee_welfare_configuration).permit(:company_id, :welfare_name, :amount)
    end
    def goods_category_params
      params.require(:sale_course).permit(:company_id, :name)
    end
    def course_room_params
      params.require(:course_room_configuration).permit(:company_id, :studio_id, :room_name, :location, :max_contain)
    end
    def private_education_params
      params.require(:private_education_configuration).permit(:company_id, :duration)
    end
    def bonus_params
      params.require(:bonus_configuration).permit(:company_id, :bonus_percent, :one_month_sale, :total_sale)
    end

end

app/views/admin/company_configurations/_bonus.html.erb
<%= form_for(@bonus, url: update_bonus_admin_company_configurations_path, method: :post) do |f| %>
  <div>
    <span>年奖金池：</span>
    <span><%= check_box_tag :open, "1", !@bonus.new_record? %></span>
    <span>开启</span>
  </div>
  </br>
  <div class ="open_bonus" >
    <span>年奖金百分比：</span>
    <div style="margin-left: 8em;">
      <%= f.number_field :bonus_percent, required: true, style: "width:6em" %>
      <span>%</span>
      <p>每年奖金 = 每年奖金比 x 年超出目标营业额部分</p>
      <p>每年奖金将与年末平均发放于每位员工</p>
    </div>
    <span>奖金领取要求：</span>
    <div style="margin-left: 8em;">
      <span><%= f.check_box :one_month_sale %></span>
      <span>单月业绩 / 课消达标</span>
      <p>单月业务达标方可领取绩效/奖金</p>
      <span><%= f.check_box :total_sale %></span>
      <span>累计业务达标</span>
      <p>当月业务未达标，产生绩效 / 奖金，但不可领取，直至补全未达标业绩方可发放</p>
      <p>补全未达标业绩部分，不算到当月超出目标营业额部分</p>
    </div>
  </div>
  <%= submit_tag "保存" %>
<% end %>

app/views/admin/company_configurations/_company_name.html.erb
<%= form_for(@current_company, url: update_company_name_admin_company_configurations_path, method: :post, remote: true, html: { multipart: true}) do |f| %>
  <%= f.text_field :name, required: true, style: "width: 10em" %>
  <%= f.submit "保存"%>
<% end %>

app/views/admin/company_configurations/_course_private_education.html.erb
<%= form_for(@private_education, url: update_private_education_admin_company_configurations_path, method: :post, html: { multipart: true}) do |f| %>
  <tr>
    <td>私教时长</td>
    <td><%= f.number_field :duration, required: true, style: "width:6em" %>
    <td>小时</td>
  </tr>
  <tr>
    <td colspan='4'>
      <%= submit_tag "保存"%>
    </td>
  </tr>
<% end %>

app/views/admin/company_configurations/_course_room.html.erb
<ul class="row list-unstyled">
  <% @course_rooms.each do |room| %>
    <li class="col-sm-10">
      <span class="col-sm-3">所属分店: <%= room.studio.try :name %></span>&nbsp;&nbsp;
      <span class="col-sm-3">教室名称: <%= room.room_name %></span>&nbsp;&nbsp;
      <span class="col-sm-5">教室位置: <%= room.location %></span>&nbsp;&nbsp;
      <span class="col-sm-2">人数上限: <%= room.max_contain %></span>&nbsp;&nbsp;
      <%= link_to '删除','javascript:void(0)',
        onclick: "ajax_function('/admin/company_configurations/destroy_configuration', 'course_room', 'CourseRoomConfiguration', #{room.id})",
        id: "delete_course_room#{room.id}" %>
    </li>
  <% end %>

  <%= form_for(@course_room, url: create_course_room_admin_company_configurations_path, html: { multipart: true}) do |f| %>
    <table>
      <tr>
        <td><%= f.select :studio_id, options_for_select(@current_studios.map{|u| [u.name, u.id]}), prompt: "所属分店" %></td>
        <td><%= f.text_field :room_name, required: true, placeholder: "教室名称", style: "width:10em" %></td>
        <td><%= f.text_field :location, required: true, placeholder: "教室位置", style: "width:10em" %></td>
        <td><%= f.number_field :max_contain, required: true, placeholder: "人数上限", style: "width:10em" %></td>
      </tr>
      <tr>
        <td colspan='2'>
          <%= f.submit "添加" %>
        </td>
      </tr>
    </table>
  <% end %>
</ul>

app/views/admin/company_configurations/bonus.html.erb
<script type="text/javascript" language="javascript" charset="utf-8">
$(".header-con li a").removeClass("open-menu");
$(".header-con li #configuration").addClass("open-menu");
</script>
<div class="boxed clearfix">
  <div class="common-tit">
    <h2>商品设置</h2>
    <span>公司设置 > 课程设置</span>
  </div>
  <div class="ad-box">
    <div class="account-infor">
      <%= render partial: "company_configuration_nav" %>
      <h3>
        <em>*</em>
        <span>公司设置</span>
      </h3>
      <%= form_for(@current_company, url: update_company_name_admin_company_configurations_path, method: :post, remote: true, html: { multipart: true}) do |f| %>
        <div class="comp-set clearfix">
          <%= f.text_field :name, required: true, placeholder: "公司名称", id: "setCompany" %>
          <%= f.submit "保存", class: "set-combtn" %>
        </div>
      <% end %>
      <h3>
        <span>年终奖设置</span>
      </h3>


<%= form_for(@bonus, url: update_bonus_admin_company_configurations_path, method: :post) do |f| %>
      <div class="comp-setbox">
        <div class="comp-set">
          <div class="annual-bonus clearfix">
            <span>年终奖池:</span>
            <div class="bonus-con">
              <div class="sub-con">
                <div class="test-check">
                  <%= check_box_tag :open, "1", !@bonus.new_record?, class: "ck" %>
                  <div class="check" id="bonusCheck">
                    <span></span>
                  </div>
                </div>
              </div>
              <em>开启</em>
              <%= f.text_field :bonus_percent, required: true, placeholder: "整数", id: "bonusNum"%>
              <i>勾选后必填！</i>
            </div>
          </div>
          <div class="annual-bonus clearfix open_bonus">
            <span>奖金领取要求:</span>
            <div class="bonus-con">
              <div class="bo-con">
                <div class="sub-con">
                  <div class="test-check">
                    <%= f.check_box :one_month_sale, class: "ck" %>
                    <div class="check">
                      <span></span>
                    </div>
                  </div>
                </div>
                <b>单月业绩／课消达标</b>
                <p>单月业务达标方可领取绩效/奖金</p>
              </div>
              <div class="bo-con">
                <div class="sub-con">
                  <div class="test-check">
                    <%= f.check_box :total_sale, class: "ck" %>
                    <div class="check">
                      <span></span>
                    </div>
                  </div>
                </div>
                <b>累计业务达标</b>
                <p>当月业务未达标，产生绩效/奖金，但不可领取，直至补全未达标业绩方可发放补全未达标业绩部分，不算到当月超出目标营业额部分</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <%= submit_tag "保存", class: "bonus-sbtn" %>
  <% end %>
  </div>
</div>

<script src="/assets/js/common-list.js"></script>
<script>
$(".set-combtn").on("click", function() {
  if ($("#setCompany").val() == "") {
    $("#setCompany").css({
      "border" : "1px solid #ff5a60"
    });
  } else {
    $("#setCompany").css({
      "border" : "1px solid #9ea0b7"
    });
  }
})
$(".bonus-sbtn").on("click", function() {
  var bonusT = true;
  if ($("#bonusCheck").attr("checked") == "checked" && $("#bonusNum").val() == "") {
    bonus = false;
    $("#bonusNum").next("i").css({
      "display" : "inline"
    });
  } else {
    $("#bonusNum").next("i").css({
      "display" : "none"
    });
  }
  if (bonusT) {
    console.log("通过验证");
  };
})
</script>

<script>
  var a = <%= !@bonus.new_record? %>;
  if (a) {
    $(".open_bonus").css({
      "display" : "block"
    });
    $("#bonusNum").css({
      "display" : "inline"
    });
    $("#bonusCheck").addClass("ad-checked").children().css({
      "display": "block"
    });
    if ($(".open_bonus .ck").eq(0).attr("checked") == "checked"){
      $(".open_bonus .ck").eq(0).next().addClass("ad-checked").children().css({
        "display": "block"
      });
    }
    if ($(".open_bonus .ck").eq(1).attr("checked") == "checked"){
      $(".open_bonus .ck").eq(1).next().addClass("ad-checked").children().css({
        "display": "block"
      });
    }
  }
  else {
    $(".open_bonus").css({
      "display" : "none"
    });
    $("#bonusNum").css({
      "display" : "none"
    });
  }
$(".check").on("click",function(){
  if ($(this).hasClass("ad-checked")){
    $(this).prev().attr("check","checked");
  }
  else{
    $(this).prev().attr("check","");
  }
});

$("#bonusCheck").on("click", function(){
  if ($(this).hasClass("ad-checked")){
      $(".open_bonus").css({
        "display" : "block"
      });
      $("#bonusNum").css({
        "display" : "inline"
      });
  }
  else{
      $(".open_bonus").css({
        "display" : "none"
      });
      $("#bonusNum").css({
        "display" : "none"
      });
  }
  })
</script>

app/views/admin/company_configurations/create_employee_welfare.js.erb
$(".welfare-plan").html("<%= j render "employee_welfare" %>")

app/views/admin/company_configurations/employee.html.erb
<script type="text/javascript" language="javascript" charset="utf-8">
$(".header-con li a").removeClass("open-menu");
$(".header-con li #configuration").addClass("open-menu");
</script>
<div class="boxed clearfix">
  <div class="common-tit">
    <h2>商品设置</h2>
    <span>公司设置 > 商品设置</span>
  </div>
  <div class="ad-box">
    <div class="account-infor">
      <%= render partial: "company_configuration_nav" %>
      <h3>
        <span>部门设置</span>
      </h3>
      <div class="comp-set">
        <ul class="commod">
          <% @default_departments.each do |department| %>
            <li>
              <span>工作室部门:</span>
              <em><%= department.department_name %></em>
            </li>
          <% end %>
        </ul>
        <% @private_departments.each do |department| %>
          <div class="com-stuw clearfix">
            <ul class="com-stwcon">
              <li>
                <span>工作室部门:</span>
                <em><%= department.department_name %></em>
              </li>
            </ul>
            <div>
              <%= link_to '删除','javascript:void(0)',
                onclick: "ajax_function('/admin/company_configurations/destroy_configuration', 'department', 'DepartmentConfiguration', #{department.id})",
                id: "delete_department#{department.id}", class: "comm-del" %>
          </div>
          </div>
        <% end %>
        <%= form_for(@department, url: create_department_admin_company_configurations_path, html: { multipart: true}) do |f| %>
          <div class="com-stua cstua clearfix">
            <ul class="com-stcon">
              <li>
                <span>工作室部门:</span>
                <%= f.text_field :department_name %>
              </li>
            </ul>
            <%= f.submit "添加", class: "comm-add" %>
          </div>
        <% end %>
      </div>
      <h3>
        <span>职位设置</span>
      </h3>
      <div class="comp-setbox">
        <div class="comp-set">
          <ul class="commod">
            <% @default_positions.each do |position| %>
              <li>
                <span>职位名称:</span>
                <em><%= position.position_name %></em>
              </li>
            <% end %>
          </ul>
          <% @private_positions.each do |position| %>
            <div class="com-stuw clearfix">
              <ul class="com-stwcon">
                <li>
                  <span>职位名称:</span>
                  <em><%= position.position_name %></em>
                </li>
              </ul>
              <div>
                <%= link_to '删除','javascript:void(0)',
                  onclick: "ajax_function('/admin/company_configurations/destroy_configuration', 'position', 'PositionConfiguration', #{position.id})",
                  id: "delete_position#{position.id}", class: "comm-del" %>
            </div>
            </div>
          <% end %>
          <%= form_for(@position, url: create_position_admin_company_configurations_path, html: { multipart: true}) do |f| %>
            <div class="com-stua cstua clearfix">
              <ul class="com-stcon">
                <li>
                  <span>职位名称:</span>
                  <%= f.text_field :position_name %>
                </li>
              </ul>
              <%= f.submit "添加", class: "comm-add" %>
            </div>
          <% end %>
        </div>
      </div>
      <h3>
        <span>导师等级</span>
      </h3>
      <div class="comp-setbox">
        <div class="comp-set">
          <% @teacher_levels.each do |teacher_level| %>
            <div class="com-stuw clearfix">
              <ul class="com-stwcon">
                <li>
                  <span>导师等级:</span>
                  <em><%= teacher_level.teacher_level %></em>
                </li>
              </ul>
              <div>
                <%= link_to '删除','javascript:void(0)',
                  onclick: "ajax_function('/admin/company_configurations/destroy_configuration', 'teacher_level', 'TeacherLevelConfiguration', #{teacher_level.id})",
                  id: "delete_teacher_level#{teacher_level.id}", class: "comm-del" %>
            </div>
            </div>
          <% end %>
          <%= form_for(@teacher_level, url: create_teacher_level_admin_company_configurations_path, html: { multipart: true}) do |f| %>
            <div class="com-stua cstua clearfix">
              <ul class="com-stcon">
                <li>
                  <span>导师等级:</span>
                  <%= f.text_field :teacher_level %>
                </li>
              </ul>
              <%= f.submit "添加", class: "comm-add" %>
            </div>
          <% end %>
        </div>
      </div>
      <h3>
        <span>员工福利设置</span>
      </h3>
      <div class="comp-setbox">
        <div class="comp-set">
          <% @employee_welfares.each do |welfare| %>
            <div class="hrw-welfare clearfix">
              <ul class="hrw-con">
                <li>
                  <span>福利名称:</span>
                  <em><%= welfare.welfare_name %></em>
                </li>
                <li>
                  <span>福利金额:</span>
                  <em><%= welfare.amount %>元/月</em>
                </li>
              </ul>
              <div>
                <%= link_to '删除','javascript:void(0)',
                  onclick: "ajax_function('/admin/company_configurations/destroy_configuration', 'employee_welfare', 'EmployeeWelfareConfiguration', #{welfare.id})",
                  id: "delete_employee_welfare#{welfare.id}", class: "comm-del" %>
            </div>
            </div>
          <% end %>
          <%= form_for(@employee_welfare,:url => create_employee_welfare_admin_company_configurations_path,  html: { multipart: true}) do |f| %>
            <div class="hra-welfare clearfix">
              <ul class="hra-stcon">
                <li>
                  <span>福利名称:</span>
                  <%= f.text_field :welfare_name %>
                </li>
                <li>
                  <span>福利金额:</span>
                  <%= f.text_field :amount %>
                  <span>元/月</span>
                </li>
              </ul>
              <%= f.submit "添加", class: "comm-add" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <!-- <div class="com-sbtn">保存</div> -->
  </div>
</div>
<script src="/assets/js/common-list.js"></script>

<script>
//删除人资设置
ajax_function = function (url, type, model_name, value){
  var id="#delete_" +type +value
    if (confirm("确认删除吗？")){
      $.ajax({
        url: url,
        type:'DELETE',
        data: {
          model_name: model_name,
          value: value,
        },
        success: function(data){
          $(id).parent().parent().remove();
        },
        error:function(){
          alert("出错");
        }
      });
    }
}
</script>