config/routes.rb
Rails.application.routes.draw do

  get 'qiniu/uptoken'
  post 'qiniu/private_url'

  root 'admin/sessions#new'
  get 'sms/captcha', to: 'sms#captcha'

  namespace :admin do
    root 'main#index'

    #商城支付
    get 'shop_detail/index'
    get 'shop_detail/go_to_alipay_pc_direct_pay'
    
    get 'shop_buy/index'
    get 'shop_buy/pingpp_alipay_pc_dirct_payment' 
    

    #分店的首页
    resources :branchs

    namespace :targets do
      #意向学员分配
      resources :potential_students do
        member do
        get 'assign'
        end
        collection do
        end
      end
      #学员分配
      resources :students do
        member do
          get 'assign'
        end
      end
    end


    #用户注册
    resources :users do
      collection do
        get 'search_user_by_mobile'
        get 'user_present_or_not'
        get 'sign_up', to: "users#new"
        get 'phone', to: "users#new"
        get 'email', to: "users#email"
        get 'change_pwd', to: 'users#change_pwd'
        post 'change_pwd', to: "users#update_pwd"
      end
    end


    #用户登录与退出
    resources :sessions do
      collection do
        get "sign_in", to: "sessions#new"
        post 'sign_in', to: "sessions#create"
        get "authoriz_failed", to: "sessions#authoriz_failed"
        get :logout
      end
    end

    #固定成本设置
    resources :fixed_costs do
    end

    #分店内的数据统计
    resources :statistics do
      collection do
        get "comprehensive"
        get "commodity"
        get "curriculum"
        get "recruit"
        get "service"
        get "student"
        get "teacher"
      end
    end

    #公司那边的数据统计
    resources :statistical_datum do
      collection do
        #综合统计
        get "comprehensive"
        get "change_comprehensive"
        get "commodity"
        get "change_commodity"
        get "curriculum"
        get "change_curriculum"
        get "recruit"
        get "service"
        get "student"
        get "change_student"
        get "teacher"
        get "change_teacher"
        get "finance"
        get "resource"
      end

    end

    #服务顾问服务系统
    resources :service_consultants do

    end

    #指标的设置
    resources :targets do
      collection do
        #---- 总监指标 ----
        get 'director'
        get 'director_target'
        get 'new_director_target'
        post 'save_director_target'
        get 'edit_director_target'
        post 'update_director_target'
        #---- end -----
        #----- 市场专员 ------
        get 'market'
        get 'market_target'
        get 'new_market_target'
        post 'save_market_target'
        get 'edit_market_target'
        post 'update_market_target'
        get 'detail_market'
        get "get_market_detail_list"
        get 'assign_potential_students'
        #---------- end ----------
        #---------服务顾问--------
        get 'operator'
        get 'operator_target'
        get 'new_operator_target'
        post 'save_operator_target'
        get 'edit_operator_target'
        post 'update_operator_target'
        get 'detail_operator'
        get "get_operator_detail_list"
        #----------- end ----------
        #---------导师指标---------
        get 'teacher'
        get 'teacher_target'
        get 'new_teacher_target'
        post 'save_teacher_target'
        get 'edit_teacher_target'
        post 'update_teacher_target'
        get 'detail_teacher'
        #----------- end ----------

      end
    end

    #学员系统
    resources :students  do
      #评价或回访
      resources :student_remarks do
        collection do
          get "get_data_list"
        end
      end
      member do
        get "orders"
      end
      collection do
        post "save_student"
        get "get_student_list"
      end
    end

    #课程周表
    resources :course_weeks do
      member do
        get "appointment"
        get "student_check"
        get "teacher_check"
      end
      collection do
        get "get_course_week"
        post "check_in"
        get "new_private_check_in"
        post "private_check_in"
        post "teacher_check_in"
        post "appointmented"
        get "get_pay_way"
        delete "destroy_appointment_record"
      end
    end

    #课程设置
    resources :course_infos do
      member do
        delete "close_course"
      end
      collection do
        get "get_course_list"
        post "update_course"
        delete "destroy_appointment_record"
      end
    end

    #意向学员
    resources :potential_students do
      collection do
        get "new_remark"
        post "save_remark"
        get "check_student"
        post "save_student"
        get "get_student_list"
      end
    end

    #财务
    resources :finances do
      member do
        get 'edit_income'
        get 'edit_expense'
      end
      collection do
        get "laborage"
        get 'initial_state'
        post 'set_initial'
        get 'income'
        get 'expense'
        get "get_finance_list"
        get 'month_expenditure'
      end
    end

    # 商品
    resources :goods do
      member do
        get :record
        get :change_status
        get :price
        post :update_good
      end
      collection do
        get :goods_shop
        get :get_good_list
        get :new_order
        post :create_order
      end
    end

    # 导师系统
    resources :teachers do
      member do
        get :get_course_week
        get :get_course_week_detail
      end
      collection do
        get :get_teacher_search_out
        get :get_teacher_by_name_phone
        get :get_my_students_by_teacher_id
        get :get_my_record_teaching_salary
        get :get_my_students_by_teacher_id
        get :show_my_student_detail
        get :remark_my_student
        get :new_comment_in_teacher
      end
    end

    # 订单
    resources :orders do
    end

    # 公司
    resources :companies do
      collection do
        get :recharge
        get :new_studio
        get :finish_paying
        get :switch_company
      end
    end

    # 员工
    resources :employees do
      collection do
        get 'get_employee'
      end
    end

    # 分店
    resources :studios do
      collection do
        get :finish_paying
        get :switch_studio
        get :update_studio_name
      end
    end

    # 公司设置
    resources :company_configurations do
      collection do
        #删除公司设置
        delete :destroy_configuration
        delete :destroy_goods_category

        #学员设置
        get :student
        post :create_student_group
        post :create_potential_student_group

        #课程设置
        get :course
        post :create_course_room
        post :update_private_education

        #商品设置
        get :goods
        post :create_goods_category

        #人资设置
        get :employee
        post :create_department
        post :create_position
        post :create_teacher_level
        post :create_employee_welfare

        #奖金设置
        get :bonus
        post :update_company_name
        post :update_bonus
      end
    end

  end
end

app/controllers/admin/service_consultants_controller.rb
class Admin::ServiceConsultantsController < ApplicationController
  layout 'studio'

  #学员数据权限验证
  before_action :authorize_student

  def index 
    params[:paying_type] ||= "all"
    params[:sex] ||= "all"
    params[:age_group] ||= "all"
    params[:learning_status] ||= "all"
    params[:expend_status] ||= "all"
    params[:expend_level] ||= "all"
    conditions = ["1=1"]

    employee = current_company.employees.find_by_user_id(current_user.id)
    conditions << "students.sex = '#{params[:sex]}'" if params[:sex] != "all" && params[:sex].present?
    
    # 服务顾问员工id＝ 当前登陆本人员工id
    # conditions << "students.service_employee_id = #{employee.id}" 
    
    if params[:age_group].present?
      if params[:age_group] == "幼儿"
        conditions << "students.birthday between '#{Date.current - 6.year}' and '#{Date.current - 3.year}'"
      elsif params[:age_group] == "少年"
        conditions << "students.birthday between '#{Date.current - 12.year}' and '#{Date.current - 6.year}'"
      elsif params[:age_group] == "青少年"
        conditions << "students.birthday between '#{Date.current - 18.year}' and '#{Date.current - 12.year}'"
      elsif params[:age_group] == "成年"
        conditions << "students.birthday < '#{Date.current - 18.year}'"
      end
    end
    conditions << "(students.name like '%#{params[:search_student]}%' or students.mobile like '%#{params[:search_student]}%')" if params[:search_student] != "all" && params[:search_student].present?
    @employee = Employee.find_by(user_id: current_user.id, company_id: current_company.id)
    @positions = @employee.employee_of_studios.map { |em| em.position_configuration.position_name }
    @students =  Student.where(conditions.join(" and "))
      .distinct
      .paginate(page: params[:page], per_page: get_per_page_num)
  end

  def get_student_list

    params[:paying_type] ||= "all"
    params[:sex] ||= "all"
    params[:age_group] ||= "all"
    params[:learning_status] ||= "all"
    params[:expend_status] ||= "all"
    params[:expend_level] ||= "all"
    conditions = ["1=1"]

    employee = current_company.employees.find_by_user_id(current_user.id)
    conditions << "students.sex = '#{params[:sex]}'" if params[:sex] != "all" && params[:sex].present?
    conditions << "students.service_employee_id = #{employee.id}" 
    if params[:age_group].present?
      if params[:age_group] == "幼儿"
        conditions << "students.birthday between '#{Date.current - 6.year}' and '#{Date.current - 3.year}'"
      elsif params[:age_group] == "少年"
        conditions << "students.birthday between '#{Date.current - 12.year}' and '#{Date.current - 6.year}'"
      elsif params[:age_group] == "青少年"
        conditions << "students.birthday between '#{Date.current - 18.year}' and '#{Date.current - 12.year}'"
      elsif params[:age_group] == "成年"
        conditions << "students.birthday < '#{Date.current - 18.year}'"
      end
    end
    conditions << "(students.name like '%#{params[:search_student]}%' or students.mobile like '%#{params[:search_student]}%')" if params[:search_student] != "all" && params[:search_student].present?
    @employee = Employee.find_by(user_id: current_user.id, company_id: current_company.id)
    @positions = @employee.employee_of_studios.map { |em| em.position_configuration.position_name }
    @students =  Student.where(conditions.join(" and "))
      .distinct
      .paginate(page: params[:page], per_page: get_per_page_num)
  end

  def show
    @student = Student.find(params[:id])
  end

  private

  def authorize_student
    authorize Student,:service_consultant?
  end

end

app/helpers/admin/service_consultants_helper.rb
module Admin::ServiceConsultantsHelper
end

app/views/admin/service_consultants/_student.html.erb
<div class="scrollbox">
  <table>
    <thead>
      <tr>
        <th class="stul-head">头像</th>
        <th class="stul-name">姓名</th>
        <th class="stul-type">消费类型</th>
        <th class="stul-adviser">服务顾问</th>
        <th class="curl-operation">操作</th>
      </tr>
    </thead>
    <tbody>
      <% @students.each do |student| %>
        <tr>
          <td>
            <div class="as-imgbox">
              <img src="" alt="">
            </div>
          </td>
          <td class="stul-name">
            <span><%= student.name %></span>
            <% if student.is_expire %>
              <div>
                <em>即将到期</em>
              </div>
            <%end%>
          </td>
          <td>年卡</td>
          <td><%= student.service_employee.name if student.service_employee_id %></td>
          <td class="curl-operation">
            <span>[</span>
            <em><%= link_to "查看详情", admin_student_path(student) %></em>
            <span>]</span>
            <span>[</span>
            <em>消费记录</em>
            <span>]</span>
            <span>[</span>
            <em><%= link_to "评价信息", admin_student_student_remarks_path(student) %></em>
            <span>]</span>	
          </td>
        </tr>
      <%end%>
    </tbody>
  </table>
  <div class="apple_pagination" >
    <%= paginate @students, :container => false %>
  </div>
</div>

app/views/admin/service_consultants/get_student_list.js.erb
$(".curlist-con").html("<%= j render "student" %>");

app/views/admin/service_consultants/index.html.erb
<script type="text/javascript" language="javascript" charset="utf-8">
$(".menu-wrap li").removeClass("active-link");
$(".menu-wrap #service_consultant").addClass("active-link");
</script>
<div class="mask">
</div>
<div class="common-tit">
  <h2>学员列表</h2>
  <span>服务系统 &gt; 学员列表</span>
</div>
<div class="cur-list">
  <div class="cur-listbox clearfix">
    <div class="cur-ll cur-serch clearfix">
      <div class="list-box">
        <div class="downbtn">
          <span data_id="all">请选择消费类型</span>
          <em></em>
        </div>
        <ul class="dropdown-menu">
          <li data_id="all">请选择消费类型</li>
          <li data_id="年卡">年卡</li>
          <li data_id="月卡">月卡</li>
          <li data_id="次卡">次卡</li>
          <li data_id="充值卡">充值卡</li>
        </ul>
      </div>
      <div class="list-box">
        <div class="downbtn">
          <span data_id="all">性别</span>
          <em></em>
        </div>
        <ul class="dropdown-menu">
          <li data_id="all">请选择性别</li>
          <li data_id="男">男</li>
          <li data_id="女">女</li>
        </ul>
      </div>
      <div class="list-box">
        <div class="downbtn">
          <span data_id="all">请选择年龄分组</span>
          <em></em>
        </div>
        <ul class="dropdown-menu">
          <li data_id="all">请选择年龄分组</li>
          <% Company::AGE_GROUP.each do |key, value| %>
            <li data_id="<%= key %>"><%= value %></li>
          <%end%>
        </ul>
      </div>
      <div class="list-box">
        <div class="downbtn">
          <span data_id="all">请选择上课状态</span>
          <em></em>
        </div>
        <ul class="dropdown-menu">
          <li data_id="all">请选择上课状态</li>
          <li data_id="正常">正常</li>
          <li data_id="缺课">缺课</li>
        </ul>
      </div>
      <div class="list-box">
        <div class="downbtn">
          <span data_id="all">缴费状态</span>
          <em></em>
        </div>
        <ul class="dropdown-menu">
          <li data_id="all">缴费状态</li>
          <li data_id="正常">正常</li>
          <li data_id="即将到期">即将到期</li>
        </ul>
      </div>
      <div class="list-box">
        <div class="downbtn">
          <span data_id="all">消费能力</span>
          <em></em>
        </div>
        <ul class="dropdown-menu">
          <li data_id="all">消费能力</li>
          <li data_id="5-10">5-10k</li>
          <li data_id="10-20">10-20k</li>
          <li data_id="20+">20k以上</li>
        </ul>
      </div>
      <div class="i-search">
        <em></em>
        <input id="searchStu" type="text" placeholder="请输入要搜索学员的手机或名字">
      </div>
    </div>
  </div>
  <div class="curlist-con">
    <div class="scrollbox">
      <table>
        <thead>
          <tr>
            <th class="stul-head">头像</th>
            <th class="stul-name">姓名</th>
            <th class="stul-type">消费类型</th>
            <th class="stul-adviser">服务顾问</th>
            <th class="curl-operation">操作</th>
          </tr>
        </thead>
        <tbody>
          <% @students.each do |student| %>
          <tr>
            <td>
              <div class="as-imgbox">
                <img src="" alt="">
              </div>
            </td>
            <td class="stul-name">
              <span><%= student.name %></span>
              <% if student.is_expire %>
              <div>
                <em>即将到期</em>
              </div>
              <%end%>
            </td>
            <td>年卡</td>
            <td><%= student.service_employee.name if student.service_employee_id %></td>
            <td class="curl-operation">
              <span>[</span>
              <em><%= link_to "查看详情", admin_service_consultant_path(student) %></em>
              <span>]</span>
              <span>[</span>
              <em><%= link_to "评价信息", admin_student_student_remarks_path(student) %></em>
              <span>]</span>	
            </td>
          </tr>
          <%end%>
        </tbody>
      </table>
      <div class="apple_pagination">
        <%= paginate @students, :container => false %>
      </div>
    </div>
  </div>
</div>
<script src="/assets/js/common.js"></script>
<script>
$(".cur-ll .list-box li").on("click", function() {
  $(this).parent().parent().find("span").attr("data_id", $(this).attr("data_id"));
  transData();
});
$("#searchStu").change(function() {
  if ($(this).val() != "") {
    transData();
  }
});
function transData() {
  var transD = "";
  for (var i = 0; i < $(".cur-ll .list-box").length; i++) {
    switch(true) {
      case i == 0: transD += "paying_type" + "=" + $($(".cur-ll .list-box")[i]).find("span").attr("data_id") + "&";break;
      case i == 1: transD += "sex" + "=" + $($(".cur-ll .list-box")[i]).find("span").attr("data_id") + "&";break;
      case i == 2: transD += "age_group" + "=" + $($(".cur-ll .list-box")[i]).find("span").attr("data_id") + "&";break;
      case i == 3: transD += "learning_status" + "=" + $($(".cur-ll .list-box")[i]).find("span").attr("data_id") + "&";break;
      case i == 4: transD += "expend_status" + "=" + $($(".cur-ll .list-box")[i]).find("span").attr("data_id") + "&";break;
      case i == 5: transD += "expend_level" + "=" + $($(".cur-ll .list-box")[i]).find("span").attr("data_id");break;
    };
  };
  if ($("#searchStu").val() != "") {
    transD += "&" + "search_student" + "=" + $("#searchStu").val();
  };
  $.ajax({
    type:'get', url:"/admin/service_consultants/get_student_list?"+ transD,
    success: function(data) {
      if (data.error) {
        // console.log("wrong");
      } 
    }
  });
}
</script>

app/views/admin/service_consultants/index.js.erb
$(".curlist-con").html("<%= j render "student" %>");

app/views/admin/service_consultants/show.html.erb
<script type="text/javascript" language="javascript" charset="utf-8">
$(".menu-wrap li").removeClass("active-link");
$(".menu-wrap #service_consultant").addClass("active-link");
</script>
<div class="common-tit">
  <h2>学员详情</h2>
  <span><%= link_to "学员系统", admin_students_path %> &gt; 学员详情</span>
</div>
<div class="course-box">
  <h3>
    <span>基本信息</span>
  </h3>
  <div class="commo-dec clearfix">
    <div class="camera"></div>
    <ul>
      <li>
        <span>姓名:</span>
        <em><%= @student.name %></em>
      </li>
      <li>
        <span>别名:</span>
        <em><%= @student.alias_name %></em>
      </li>
      <li>
        <span>性别:</span>
        <em><%= @student.sex %></em>
      </li>
      <li>
        <span>学员分组:</span>
        <em><%= @student.student_group_configuration.group_name if @student.student_group %></em>
      </li>
      <li>
        <span>手机号:</span>
        <em><%= @student.mobile %></em>
      </li>
      <li>
        <span>微信号:</span>
        <em><%= @student.weixin %></em>
      </li>
      <li>
        <span>出生年月:</span>
        <em><%= @student.birthday %></em>
      </li>
      <li>
        <span>信息来源:</span>
        <em><%= @student.source_from %></em>
      </li>
      <li>
        <span>紧急联系人:</span>
        <em><%= @student.emergency_contact %></em>
      </li>
      <li>
        <span>紧急联系电话:</span>
        <em><%= @student.emergency_mobile %></em>
      </li>
      <li class="sd-a">
        <span>联系地址:</span>
        <em><%= @student.address %></em>
      </li>
      <li class="sd-a">
        <span>备注信息:</span>
        <% if @student.remark %>
          <em><%= @student.remark %></em>
        <% else%>
          <em><%= @student.learning_requirement %> &nbsp; <%= @student.state_of_business %> &nbsp; <%= @student.learning_intention %></em>
        <% end %>
      </li>
    </ul>
  </div>
  <h3>
    <span>相关信息</span>
  </h3>
  <div class="course-b clearfix">
    <div class="st-dein clearfix">
      <div>
        <span>市场专员:</span>
        <em><%= @student.market_employee.name if @student.market_employee_id %></em>
      </div>
      <div>
        <span>服务顾问:</span>
        <em><%= @student.service_employee.name if @student.service_employee_id %></em>
      </div>
      <div>
        <span>意向导师:</span>
        <em><%= @student.willing_teacher %></em>
      </div>
      <div>
        <span>消费能力:</span>
        <em>5k~10k</em>
      </div>
    </div>
  </div>
  <h3>
    <span>消费信息</span>
  </h3>
  <div class="course-b s-consbox clearfix">
    <% @student.student_cards.each do |sc| %>
      <div class="stu-consumption clearfix">
        <div>
          <span>消费类型:</span>
          <em><%= sc.card_type %></em>
        </div>
        <div>
          <span>当前余额:</span>
          <em>
            <% if %w{年卡 次卡}.include?(sc.card_type) %>
              -
            <%else%>
              <% if sc.card_type == "充值" %>
                <%= sc.amount%> 元 
              <% elsif %{次卡 直接售卖}.include?(sc.card_type) %>
                <%= sc.amount%> 次 
              <% end %>
            <%end%>
          </em>
        </div>
        <div>
          <span>有效期限:</span>
          <em><%= sc.invalidated_at.strftime("%Y年%m月%d日") %></em>
        </div>
      </div>
    <% end %>
  </div>
  <h3>
    <span>统计信息</span>
  </h3>
  <div class="course-b clearfix">
    <div class="st-dein clearfix">
      <div>
        <span>累计上课次数:</span>
        <em><%= @student.check_ins.count %></em>
      </div>
      <div>
        <span>累计消费金额:</span>
        <em><%= @student.accumulated_amount %></em>
      </div>
    </div>
  </div>
</div>
<script src="/assets/js/common.js"></script>