config/routes.rb
Rails.application.routes.draw do

  get 'qiniu/uptoken'
  post 'qiniu/private_url'

  root 'admin/sessions#new'
  get 'sms/captcha', to: 'sms#captcha'

  namespace :admin do
    root 'main#index'

    #商城支付
    get 'shop_detail/index'
    get 'shop_detail/go_to_alipay_pc_direct_pay'
    
    get 'shop_buy/index'
    get 'shop_buy/pingpp_alipay_pc_dirct_payment' 
    

    #分店的首页
    resources :branchs

    namespace :targets do
      #意向学员分配
      resources :potential_students do
        member do
        get 'assign'
        end
        collection do
        end
      end
      #学员分配
      resources :students do
        member do
          get 'assign'
        end
      end
    end


    #用户注册
    resources :users do
      collection do
        get 'search_user_by_mobile'
        get 'user_present_or_not'
        get 'sign_up', to: "users#new"
        get 'phone', to: "users#new"
        get 'email', to: "users#email"
        get 'change_pwd', to: 'users#change_pwd'
        post 'change_pwd', to: "users#update_pwd"
      end
    end


    #用户登录与退出
    resources :sessions do
      collection do
        get "sign_in", to: "sessions#new"
        post 'sign_in', to: "sessions#create"
        get "authoriz_failed", to: "sessions#authoriz_failed"
        get :logout
      end
    end

    #固定成本设置
    resources :fixed_costs do
    end

    #分店内的数据统计
    resources :statistics do
      collection do
        get "comprehensive"
        get "commodity"
        get "curriculum"
        get "recruit"
        get "service"
        get "student"
        get "teacher"
      end
    end

    #公司那边的数据统计
    resources :statistical_datum do
      collection do
        #综合统计
        get "comprehensive"
        get "change_comprehensive"
        get "commodity"
        get "change_commodity"
        get "curriculum"
        get "change_curriculum"
        get "recruit"
        get "service"
        get "student"
        get "change_student"
        get "teacher"
        get "change_teacher"
        get "finance"
        get "resource"
      end

    end

    #服务顾问服务系统
    resources :service_consultants do

    end

    #指标的设置
    resources :targets do
      collection do
        #---- 总监指标 ----
        get 'director'
        get 'director_target'
        get 'new_director_target'
        post 'save_director_target'
        get 'edit_director_target'
        post 'update_director_target'
        #---- end -----
        #----- 市场专员 ------
        get 'market'
        get 'market_target'
        get 'new_market_target'
        post 'save_market_target'
        get 'edit_market_target'
        post 'update_market_target'
        get 'detail_market'
        get "get_market_detail_list"
        get 'assign_potential_students'
        #---------- end ----------
        #---------服务顾问--------
        get 'operator'
        get 'operator_target'
        get 'new_operator_target'
        post 'save_operator_target'
        get 'edit_operator_target'
        post 'update_operator_target'
        get 'detail_operator'
        get "get_operator_detail_list"
        #----------- end ----------
        #---------导师指标---------
        get 'teacher'
        get 'teacher_target'
        get 'new_teacher_target'
        post 'save_teacher_target'
        get 'edit_teacher_target'
        post 'update_teacher_target'
        get 'detail_teacher'
        #----------- end ----------

      end
    end

    #学员系统
    resources :students  do
      #评价或回访
      resources :student_remarks do
        collection do
          get "get_data_list"
        end
      end
      member do
        get "orders"
      end
      collection do
        post "save_student"
        get "get_student_list"
      end
    end

    #课程周表
    resources :course_weeks do
      member do
        get "appointment"
        get "student_check"
        get "teacher_check"
      end
      collection do
        get "get_course_week"
        post "check_in"
        get "new_private_check_in"
        post "private_check_in"
        post "teacher_check_in"
        post "appointmented"
        get "get_pay_way"
        delete "destroy_appointment_record"
      end
    end

    #课程设置
    resources :course_infos do
      member do
        delete "close_course"
      end
      collection do
        get "get_course_list"
        post "update_course"
        delete "destroy_appointment_record"
      end
    end

    #意向学员
    resources :potential_students do
      collection do
        get "new_remark"
        post "save_remark"
        get "check_student"
        post "save_student"
        get "get_student_list"
      end
    end

    #财务
    resources :finances do
      member do
        get 'edit_income'
        get 'edit_expense'
      end
      collection do
        get "laborage"
        get 'initial_state'
        post 'set_initial'
        get 'income'
        get 'expense'
        get "get_finance_list"
        get 'month_expenditure'
      end
    end

    # 商品
    resources :goods do
      member do
        get :record
        get :change_status
        get :price
        post :update_good
      end
      collection do
        get :goods_shop
        get :get_good_list
        get :new_order
        post :create_order
      end
    end

    # 导师系统
    resources :teachers do
      member do
        get :get_course_week
        get :get_course_week_detail
      end
      collection do
        get :get_teacher_search_out
        get :get_teacher_by_name_phone
        get :get_my_students_by_teacher_id
        get :get_my_record_teaching_salary
        get :get_my_students_by_teacher_id
        get :show_my_student_detail
        get :remark_my_student
        get :new_comment_in_teacher
      end
    end

    # 订单
    resources :orders do
    end

    # 公司
    resources :companies do
      collection do
        get :recharge
        get :new_studio
        get :finish_paying
        get :switch_company
      end
    end

    # 员工
    resources :employees do
      collection do
        get 'get_employee'
      end
    end

    # 分店
    resources :studios do
      collection do
        get :finish_paying
        get :switch_studio
        get :update_studio_name
      end
    end

    # 公司设置
    resources :company_configurations do
      collection do
        #删除公司设置
        delete :destroy_configuration
        delete :destroy_goods_category

        #学员设置
        get :student
        post :create_student_group
        post :create_potential_student_group

        #课程设置
        get :course
        post :create_course_room
        post :update_private_education

        #商品设置
        get :goods
        post :create_goods_category

        #人资设置
        get :employee
        post :create_department
        post :create_position
        post :create_teacher_level
        post :create_employee_welfare

        #奖金设置
        get :bonus
        post :update_company_name
        post :update_bonus
      end
    end

  end
end

app/controllers/admin/course_weeks_controller.rb
class Admin::CourseWeeksController < ApplicationController

  layout "studio"

  before_action :authorize_course_week

  def index 
    begin_date = Date.current
    begin_week = begin_date.at_beginning_of_week
    course_list = current_company.courses
    
    mon = begin_week
    tue = begin_week + 1.day
    wed = begin_week + 2.day
    thu = begin_week + 3.day
    fri = begin_week + 4.day
    sat = begin_week + 5.day
    sun = begin_week + 6.day

    @monday = course_list.where(day_of_week: mon).order("course_time asc")  
    @tuesday = course_list.where(day_of_week: tue).order("course_time asc")
    @wednesday = course_list.where(day_of_week: wed).order("course_time asc")
    @thursday = course_list.where(day_of_week: thu).order("course_time asc")
    @friday = course_list.where(day_of_week: fri).order("course_time asc")
    @saturday = course_list.where(day_of_week: sat).order("course_time asc")
    @sunday = course_list.where(day_of_week: sun).order("course_time asc")
    respond_to do |format|
      format.html
      format.js
    end
    
  end

  def get_course_week 
    params[:num] ||= 0
    if params[:num].to_i == -1
      begin_date = Date.current - 7.day
    elsif params[:num].to_i == 0
      begin_date = Date.current
    elsif params[:num].to_i == 1
      begin_date = Date.current + 7.day
    end

    begin_week = begin_date.at_beginning_of_week
    course_list = current_company.courses
    
    mon = begin_week
    tue = begin_week + 1.day
    wed = begin_week + 2.day
    thu = begin_week + 3.day
    fri = begin_week + 4.day
    sat = begin_week + 5.day
    sun = begin_week + 6.day

    @monday = course_list.where(day_of_week: mon).order("course_time asc")  
    @tuesday = course_list.where(day_of_week: tue).order("course_time asc")
    @wednesday = course_list.where(day_of_week: wed).order("course_time asc")
    @thursday = course_list.where(day_of_week: thu).order("course_time asc")
    @friday = course_list.where(day_of_week: fri).order("course_time asc")
    @saturday = course_list.where(day_of_week: sat).order("course_time asc")
    @sunday = course_list.where(day_of_week: sun).order("course_time asc")
    
  end

  def show
    @course = Course.find(params[:id])
    @check_ins = CheckIn.where(" course_id = :course_id and student_id is not NULL",course_id: @course.id)
    if @course.course_info.appointmented_or_not
      @appointment_records = AppointmentRecord.where("course_id = :course_id", course_id: @course.id)
    end
  end


  def appointment 
    @course = Course.find(params[:id])
    if @course.appointment_records.map(&:student_id).size > 0
    appointmented_student = Student.where("id in (#{@course.appointment_records.map(&:student_id).uniq.join(",")})")
    @students = current_company.student - appointmented_student 
    else
    @students = current_company.student
    end
    @appointment = AppointmentRecord.new(course_id: @course.id )
  end

  def appointmented
    if params[:appointment_record][:student_id].present?
      
      @course = Course.find_by_id(params[:appointment_record][:course_id]) 
      appointment_record = AppointmentRecord.new(appointment_record_params)
      appointment_record.course_info_id = @course.course_info.id
      appointment_record.appointment_at = Time.now
      appointment_record.operated_by = Employee.find_by(company_id: current_company.id, user_id: current_user.id).id
      if appointment_record.save
        @flag = true
        @message = "预约成功!"
      else
        @flag = false
        @message = "预约失败!"
      end
    else
        @flag = false
        @message = "预约失败 请检查信息是否完整!"
    end
  end

  def student_check
    @course = Course.find(params[:id])
    if @course.course_info.appointmented_or_not
      @students =  @course.appointment_records.map {|ar| ar.student }.uniq
    else
      @students = current_company.student
    end
    @check_in = CheckIn.new(course_id: @course.id)
    @pay_ways = @course.course_info.paying_ways.map(&:pay_type)
    if @course.course_info.sale_or_not
      @pay_ways.push("直接售卖")
    end
  end

  def teacher_check
    @course = Course.find(params[:id])
    @teacher = @course.course_info.teacher
    @check_in = CheckIn.new(course_id: @course.id, teacher_id: @teacher.id)
  end

  def teacher_check_in
    @check_in = CheckIn.new(check_in_params)
    @check_in.checked_at = Time.now
    @check_in.operated_by = Employee.find_by(company_id: current_company.id, user_id: current_user.id).id
    @check_in.save!
  end

  #new private check in
  def new_private_check_in
    @course = Course.find(params[:id])
    @students = @course.appointment_records.map {|ar| ar.student }.uniq
    check_in = CheckIn.new(course_id: @course.id)
  end
  
  #私教课签到
  def private_check_in
    if params[:check_in][:student_id].present?
      @check_in = CheckIn.new(check_in_params)
      @course_info = @check_in.course.course_info
      @check_in.checked_at = Time.now
      @check_in.operated_by = Employee.find_by(company_id: current_company.id, user_id: current_user.id).id
      if @check_in.save!
        @flag = true
      else
        @flag = false
      end
    else
      @flag = false
    end
  end

  def check_in

    Rails.logger.info("ceshi 222222222222!!!")
    if params[:check_in][:student_id].present? && params[:check_in][:pay_way].present?
      Rails.logger.info("ceshi 11111111111!!!")
      @check_in = CheckIn.new(check_in_params)
      @course_info = @check_in.course.course_info
      @check_in.checked_at = Time.now
      @check_in.operated_by = Employee.find_by(company_id: current_company.id, user_id: current_user.id).id
      Rails.logger.info("ceshi !!!")
      if @check_in.save!
        Rails.logger.info("ceshi #############")
        student = @check_in.student
        unless %w{年卡 月卡}.include?(@check_in.pay_way)
          @student_cards = student.student_cards.where(card_type: @check_in.pay_way).where("amount > 0 and invalidated_at > '#{Date.current}'").order(amount: :asc)
          if @check_in.pay_way == "直接售卖"
            #找到买 直接售卖的那个卡
            @student_card = @student_cards.where(course_info_id: @course_info.id).first
            if @student_card.present?
              #学生直接购买了课
              @student_card.amount = 0 
              @student_card.save!
              #若是打包课 这记录还剩多少次
              if @course_info.sale_type == "打包售卖课程"  
                overplus = @course_info.period - 1
                PackSale.create!(course_info_id: @course_info.id, student_id: student.id, amount: overplus) 
              end
              #课程核算 
              reckon_price = @student_card.price
              course_reckon = CourseReckon.create!(studio_id: current_studio.id ,course_id: @check_in.course_id,course_info_id: @course_info.id, student_id: student.id, teacher_id: @course_info.teacher.id, pay_way: @check_in.pay_way, amount: reckon_price)
            end
          elsif @check_in.pay_way == "打包购买"
            @pack_sale = PackSale.where(course_info_id: @course_info.id, student_id: student.id).where("amount > 0").first 
            @pack_sale.amount - 1
            @pack_sale.save!
          else
            #需要消耗的数量
            @student_card = @student_cards.first;
            amount = @course_info.paying_ways.where(pay_type: @check_in.pay_way).first.amount
            if @student_card.card_type == "充值"
            reckon_price = amount
            else
            reckon_price = @student_card.price * amount
            end
            #导师课消
            course_reckon = CourseReckon.create!(studio_id: current_studio.id, course_id: @check_in.course_id,course_info_id: @course_info.id, student_id: student.id, teacher_id: @course_info.teacher.id,pay_way: @check_in.pay_way, amount: reckon_price)
            @student_cards.each do |scard|
              if scard.amount <  amount
                amount = amount - scard.amount
                scard.amount = 0 
                scard.save!
              elsif scard.amount > amount
                scard.amount = scard.amount - amount
                amount = 0
                scard.save!
                break
              end
            end
            #若是打包课 这记录还剩多少次
          #  if @course_info.sale_type == "打包售卖课程"  
          #    overplus = @course_info.period - 1
          #    PackSale.create!(course_info_id: @course_info.id, student_id: student.id, amount: overplus) 
          #  end
          end
          @flag = true
        else
          course_reckon = CourseReckon.create!(studio_id: current_studio.id, course_id: @check_in.course_id, course_info_id: @course_info.id, student_id: student.id, teacher_id: @course_info.teacher.id,pay_way: @check_in.pay_way)
          @flag = true
        end
      end
    else
      @flag = false
    end
  end

  def get_pay_way
    @course_info = CourseInfo.find_by_id(params[:course_info_id])
    @student = Student.find_by_id(params[:student_id])
    if @course_info.sale_type == "打包售卖课程"
      pack_sale = @course_info.pack_sales.where("amount > 0  and  student_id = :student_id", student_id: @student.id).first 
      if pack_sale.present?
        @new_pay_ways = ["打包购买"] 
      else
        pay_ways = @course_info.paying_ways.map(&:pay_type)
        if @course_info.sale_or_not
          pay_ways.push("直接售卖")
        end
        card_type = @student.student_cards.map(&:card_type).uniq
        if card_type.include?("直接售卖")
          unless StudentCard.where(card_type: "直接售卖",course_info_id: @course_info.id).where(" amount > 0 ").first
            card_type - ["直接售卖"]
          end
        end
        @new_pay_ways = pay_ways & card_type
      end
    else
      pay_ways = @course_info.paying_ways.map(&:pay_type)
      if @course_info.sale_or_not
        pay_ways.push("直接售卖")
      end
      card_type = @student.student_cards.map(&:card_type).uniq
      if card_type.include?("直接售卖")
        unless StudentCard.where(card_type: "直接售卖",course_info_id: @course_info.id).where(" amount > 0 ").first.present?
          card_type - ["直接售卖"]
        end

app/helpers/admin/course_weeks_helper.rb
module Admin::CourseWeeksHelper
end

app/views/admin/course_weeks/_private_student.html.erb
<div class="mask-box">
  <%= form_for(@check_in, :url => private_check_in_admin_course_weeks_path, method: :post, remote:true)  do |f|%>
    <div class="mask-head">
      <h4>学员预约</h4>
      <span></span>
    </div>
    <div class="mask-con">
      <div class="mask-marc">
        <ul>
          <li>
            <span>选择学员:</span>
            <input type="" name="appointment_record[student_id]" id="student_id">
            <div class="single-box">
              <div class="single-downbtn">
                <span>学员列表</span> 
                <em></em>
              </div>
              <div class="single-dropdown">
                <em></em>
                <input type="text" placeholder="搜索">
                <ul>
                  <% @students.each do |stu| %>
                    <li data_id="<%= stu.id %>"><%= stu.name %></li>
                  <%end%>
                </ul>
              </div>
            </div>
          </li>
          <li>
            <span>选择课程:</span>
            <em><%= @course.course_info.name %></em>
          </li>
          <li>
            <span>课程导师:</span>
            <em><%= @course.course_info.teacher.name %></em>
          </li>
          <li>
            <span>上课教室:</span>
            <em><%= @course.course_info.room.room_name %></em>
          </li>
          <li>
            <span>上课时间:</span>
            <em><%= @course.course_time.strftime("%Y-%m-%d %H:%M") %></em>
          </li>
        </ul>
      </div>
    </div>
    <%= f.hidden_field :course_id %>
    <div ><%= f.submit "确认签到", :class => "mask-confirm" %></div>
  <%end%>
</div>
<script type="text/javascript" language="javascript" charset="utf-8">
$(".single-downbtn").on("click", function() {
  if ($(this).next(".single-dropdown").hasClass("menuopen")) {
    $(this).next(".single-dropdown").removeClass("menuopen");
  } else {
    $(this).next(".single-dropdown").addClass("menuopen");
    $(this).parent().hover(function() {

    }, function() {
      $(this).children(".single-dropdown").removeClass("menuopen");
    });
    $(".menuopen li").on("click", function() {
      $(this).parent().parent().removeClass("menuopen");
      $(this).parent().parent().parent().find("span").text($(this).text());
      $(this).parent().parent().find("input").val("");
      $(".single-dropdown li").removeClass("mul-hide");
      $("#student_id").val($(this).attr("data_id"));
    });
  };
});
</script>

app/views/admin/course_weeks/_ways.html.erb
<div class="downbtn">
  <span>已购买卡种</span>
  <em></em>
</div>
<ul class="dropdown-menu ways">
  <% @new_pay_ways.each do |pw| %>
    <li data_id="<%= pw %>"><%= pw %></li>
  <% end %>
</ul>

app/views/admin/course_weeks/_week_list.html.erb
<div class="scrollbox" id="weekBox">
  <table>
    <thead>
      <tr>
        <th class="timeta-name">课程名称</th>
        <th class="timeta-type">课程类型</th>
        <th class="timeta-tea">导师</th>
        <th class="timeta-time">时间</th>
        <th class="timeta-class">教室</th>
        <th class="curl-operation">操作</th>
      </tr>
    </thead>
    <tbody>
      <% @monday.each do |course| %>
        <tr>
          <td><%= course.course_info.name %></td>
          <td><%= course.course_info.course_type %></td>
          <td><%= course.course_info.teacher.name %></td>
          <td><%= course.course_time.strftime("%Y-%m-%d %H:%M") %></td>
          <td><%= course.course_info.room.room_name %></td>
          <td class="curl-operation">
            <span>[</span>
            <em><%= link_to "查看详情", admin_course_week_path(course) %></em>
            <span>]</span>
            <span>[</span>
            <em><%= link_to "学员签到", student_check_admin_course_week_path(course),remote: true %></em>
            <span>]</span>
            <% unless course.teacher_checked(course.course_info.teacher) %>
              <span>[</span>
              <em><%= link_to "导师签到", teacher_check_admin_course_week_path(course),remote: true %></em>
              <span>]</span>
            <%end%>
          </td>
        </tr>
      <%end%>
    </tbody>
  </table>
  <!-- 2 -->
  <table>
    <thead>
      <tr>
        <th class="timeta-name">课程名称</th>
        <th class="timeta-type">课程类型</th>
        <th class="timeta-tea">导师</th>
        <th class="timeta-time">时间</th>
        <th class="timeta-class">教室</th>
        <th class="curl-operation">操作</th>
      </tr>
    </thead>
    <tbody>
      <% @tuesday.each do |course| %>
        <tr>
          <td><%= course.course_info.name %></td>
          <td><%= course.course_info.course_type %></td>
          <td><%= course.course_info.teacher.name %></td>
          <td><%= course.course_time.strftime("%Y-%m-%d %H:%M") %></td>
          <td><%= course.course_info.room.room_name %></td>
          <td class="curl-operation">
            <span>[</span>
            <em><%= link_to "查看详情", admin_course_week_path(course) %></em>
            <span>]</span>
            <span>[</span>
            <em><%= link_to "学员签到", student_check_admin_course_week_path(course),remote: true %></em>
            <span>]</span>
            <% unless course.teacher_checked(course.course_info.teacher) %>

              <span>[</span>
              <em><%= link_to "导师签到", teacher_check_admin_course_week_path(course),remote: true %></em>
              <span>]</span>
            <%end%>
          </td>
        </tr>
      <%end%>
    </tbody>
  </table>
  <!-- 3 -->
  <table>
    <thead>
      <tr>
        <th class="timeta-name">课程名称</th>
        <th class="timeta-type">课程类型</th>
        <th class="timeta-tea">导师</th>
        <th class="timeta-time">时间</th>
        <th class="timeta-class">教室</th>
        <th class="curl-operation">操作</th>
      </tr>
    </thead>
    <tbody>
      <% @wednesday.each do |course| %>
        <tr>
          <td><%= course.course_info.name %></td>
          <td><%= course.course_info.course_type %></td>
          <td><%= course.course_info.teacher.name %></td>
          <td><%= course.course_time.strftime("%Y-%m-%d %H:%M") %></td>
          <td><%= course.course_info.room.room_name %></td>
          <td class="curl-operation">
            <span>[</span>
            <em><%= link_to "查看详情", admin_course_week_path(course) %></em>
            <span>]</span>
            <span>[</span>
            <em><%= link_to "学员签到", student_check_admin_course_week_path(course),remote: true %></em>
            <span>]</span>
            <% unless course.teacher_checked(course.course_info.teacher) %>

              <span>[</span>
              <em><%= link_to "导师签到", teacher_check_admin_course_week_path(course),remote: true %></em>
              <span>]</span>
            <%end%>
          </td>
        </tr>
      <% end -%>
    </tbody>
  </table>
  <!-- 4 -->
  <table>
    <thead>
      <tr>
        <th class="timeta-name">课程名称</th>
        <th class="timeta-type">课程类型</th>
        <th class="timeta-tea">导师</th>
        <th class="timeta-time">时间</th>
        <th class="timeta-class">教室</th>
        <th class="curl-operation">操作</th>
      </tr>
    </thead>
    <tbody>
      <% @thursday.each do |course| %>
        <tr>
          <td><%= course.course_info.name %></td>
          <td><%= course.course_info.course_type %></td>
          <td><%= course.course_info.teacher.name %></td>
          <td><%= course.course_time.strftime("%Y-%m-%d %H:%M") %></td>
          <td><%= course.course_info.room.room_name %></td>
          <td class="curl-operation">
            <span>[</span>
            <em><%= link_to "查看详情", admin_course_week_path(course) %></em>
            <span>]</span>
            <span>[</span>
            <em><%= link_to "学员签到", student_check_admin_course_week_path(course),remote: true %></em>
            <span>]</span>
            <% unless course.teacher_checked(course.course_info.teacher) %>

              <span>[</span>
              <em><%= link_to "导师签到", teacher_check_admin_course_week_path(course),remote: true %></em>
              <span>]</span>
            <%end%>
          </td>
        </tr>
      <%end%>
    </tbody>
  </table>
  <!-- 5 -->
  <table>
    <thead>
      <tr>
        <th class="timeta-name">课程名称</th>
        <th class="timeta-type">课程类型</th>
        <th class="timeta-tea">导师</th>
        <th class="timeta-time">时间</th>
        <th class="timeta-class">教室</th>
        <th class="curl-operation">操作</th>
      </tr>
    </thead>
    <tbody>
      <% @friday.each do |course| %>
        <tr>
          <td><%= course.course_info.name %></td>
          <td><%= course.course_info.course_type %></td>
          <td><%= course.course_info.teacher.name %></td>
          <td><%= course.course_time.strftime("%Y-%m-%d %H:%M") %></td>
          <td><%= course.course_info.room.room_name %></td>
          <td class="curl-operation">
            <span>[</span>
            <em><%= link_to "查看详情", admin_course_week_path(course) %></em>
            <span>]</span>
            <span>[</span>
            <em><%= link_to "学员签到", student_check_admin_course_week_path(course),remote: true %></em>
            <span>]</span>
            <% unless course.teacher_checked(course.course_info.teacher) %>
              <span>[</span>
              <em><%= link_to "导师签到", teacher_check_admin_course_week_path(course),remote: true %></em>
              <span>]</span>
            <%end%>
          </td>
        </tr>
      <% end -%>
    </tbody>
  </table>
  <!-- 6 -->
  <table>
    <thead>
      <tr>
        <th class="timeta-name">课程名称</th>
        <th class="timeta-type">课程类型</th>
        <th class="timeta-tea">导师</th>
        <th class="timeta-time">时间</th>
        <th class="timeta-class">教室</th>
        <th class="curl-operation">操作</th>
      </tr>
    </thead>
    <tbody>
      <% @saturday.each do |course| %>
        <tr>
          <td><%= course.course_info.name %></td>
          <td><%= course.course_info.course_type %></td>
          <td><%= course.course_info.teacher.name %></td>
          <td><%= course.course_time.strftime("%Y-%m-%d %H:%M") %></td>
          <td><%= course.course_info.room.room_name %></td>
          <td class="curl-operation">
            <span>[</span>
            <em><%= link_to "查看详情", admin_course_week_path(course) %></em>
            <span>]</span>
            <span>[</span>
            <em><%= link_to "学员签到", student_check_admin_course_week_path(course),remote: true %></em>
            <span>]</span>
            <% unless course.teacher_checked(course.course_info.teacher) %>
              <span>[</span>
              <em><%= link_to "导师签到", teacher_check_admin_course_week_path(course),remote: true %></em>
              <span>]</span>
            <%end%>
          </td>
        </tr>
      <% end -%>
    </tbody>
  </table>
  <!-- 7 -->
  <table>
    <thead>
      <tr>
        <th class="timeta-name">课程名称</th>
        <th class="timeta-type">课程类型</th>
        <th class="timeta-tea">导师</th>
        <th class="timeta-time">时间</th>
        <th class="timeta-class">教室</th>
        <th class="curl-operation">操作</th>
      </tr>
    </thead>
    <tbody>
      <% @sunday.each do |course| %>
        <tr>
          <td><%= course.course_info.name %></td>
          <td><%= course.course_info.course_type %></td>
          <td><%= course.course_info.teacher.name %></td>
          <td><%= course.course_time.strftime("%Y-%m-%d %H:%M") %></td>
          <td><%= course.course_info.room.room_name %></td>
          <td class="curl-operation">
            <span>[</span>
            <em><%= link_to "查看详情", admin_course_week_path(course) %></em>
            <span>]</span>
            <span>[</span>
            <em><%= link_to "学员签到", student_check_admin_course_week_path(course),remote: true %></em>
            <span>]</span>
            <% unless course.teacher_checked(course.course_info.teacher) %>
              <span>[</span>
              <em><%= link_to "导师签到", teacher_check_admin_course_week_path(course),remote: true %></em>
              <span>]</span>
            <%end%>
          </td>
        </tr>
      <% end -%>
    </tbody>
  </table>
</div>

app/views/admin/course_weeks/appointmented.js.erb
alert("<%= @message %>");
$(".mask").css({
  "display" : "none"
});
$(".mask").html("");

app/views/admin/course_weeks/check_in.js.erb
<% if @flag %>
    window.location.href = "/admin/course_weeks";
<%else%>
    alert("签到失败 请检查");
<%end%>   