config/routes.rb
Rails.application.routes.draw do

  get 'qiniu/uptoken'
  post 'qiniu/private_url'

  root 'admin/sessions#new'
  get 'sms/captcha', to: 'sms#captcha'

  namespace :admin do
    root 'main#index'

    #商城支付
    get 'shop_detail/index'
    get 'shop_detail/go_to_alipay_pc_direct_pay'
    
    get 'shop_buy/index'
    get 'shop_buy/pingpp_alipay_pc_dirct_payment' 
    

    #分店的首页
    resources :branchs

    namespace :targets do
      #意向学员分配
      resources :potential_students do
        member do
        get 'assign'
        end
        collection do
        end
      end
      #学员分配
      resources :students do
        member do
          get 'assign'
        end
      end
    end


    #用户注册
    resources :users do
      collection do
        get 'search_user_by_mobile'
        get 'user_present_or_not'
        get 'sign_up', to: "users#new"
        get 'phone', to: "users#new"
        get 'email', to: "users#email"
        get 'change_pwd', to: 'users#change_pwd'
        post 'change_pwd', to: "users#update_pwd"
      end
    end


    #用户登录与退出
    resources :sessions do
      collection do
        get "sign_in", to: "sessions#new"
        post 'sign_in', to: "sessions#create"
        get "authoriz_failed", to: "sessions#authoriz_failed"
        get :logout
      end
    end

    #固定成本设置
    resources :fixed_costs do
    end

    #分店内的数据统计
    resources :statistics do
      collection do
        get "comprehensive"
        get "commodity"
        get "curriculum"
        get "recruit"
        get "service"
        get "student"
        get "teacher"
      end
    end

    #公司那边的数据统计
    resources :statistical_datum do
      collection do
        #综合统计
        get "comprehensive"
        get "change_comprehensive"
        get "commodity"
        get "change_commodity"
        get "curriculum"
        get "change_curriculum"
        get "recruit"
        get "service"
        get "student"
        get "change_student"
        get "teacher"
        get "change_teacher"
        get "finance"
        get "resource"
      end

    end

    #服务顾问服务系统
    resources :service_consultants do

    end

    #指标的设置
    resources :targets do
      collection do
        #---- 总监指标 ----
        get 'director'
        get 'director_target'
        get 'new_director_target'
        post 'save_director_target'
        get 'edit_director_target'
        post 'update_director_target'
        #---- end -----
        #----- 市场专员 ------
        get 'market'
        get 'market_target'
        get 'new_market_target'
        post 'save_market_target'
        get 'edit_market_target'
        post 'update_market_target'
        get 'detail_market'
        get "get_market_detail_list"
        get 'assign_potential_students'
        #---------- end ----------
        #---------服务顾问--------
        get 'operator'
        get 'operator_target'
        get 'new_operator_target'
        post 'save_operator_target'
        get 'edit_operator_target'
        post 'update_operator_target'
        get 'detail_operator'
        get "get_operator_detail_list"
        #----------- end ----------
        #---------导师指标---------
        get 'teacher'
        get 'teacher_target'
        get 'new_teacher_target'
        post 'save_teacher_target'
        get 'edit_teacher_target'
        post 'update_teacher_target'
        get 'detail_teacher'
        #----------- end ----------

      end
    end

    #学员系统
    resources :students  do
      #评价或回访
      resources :student_remarks do
        collection do
          get "get_data_list"
        end
      end
      member do
        get "orders"
      end
      collection do
        post "save_student"
        get "get_student_list"
      end
    end

    #课程周表
    resources :course_weeks do
      member do
        get "appointment"
        get "student_check"
        get "teacher_check"
      end
      collection do
        get "get_course_week"
        post "check_in"
        get "new_private_check_in"
        post "private_check_in"
        post "teacher_check_in"
        post "appointmented"
        get "get_pay_way"
        delete "destroy_appointment_record"
      end
    end

    #课程设置
    resources :course_infos do
      member do
        delete "close_course"
      end
      collection do
        get "get_course_list"
        post "update_course"
        delete "destroy_appointment_record"
      end
    end

    #意向学员
    resources :potential_students do
      collection do
        get "new_remark"
        post "save_remark"
        get "check_student"
        post "save_student"
        get "get_student_list"
      end
    end

    #财务
    resources :finances do
      member do
        get 'edit_income'
        get 'edit_expense'
      end
      collection do
        get "laborage"
        get 'initial_state'
        post 'set_initial'
        get 'income'
        get 'expense'
        get "get_finance_list"
        get 'month_expenditure'
      end
    end

    # 商品
    resources :goods do
      member do
        get :record
        get :change_status
        get :price
        post :update_good
      end
      collection do
        get :goods_shop
        get :get_good_list
        get :new_order
        post :create_order
      end
    end

    # 导师系统
    resources :teachers do
      member do
        get :get_course_week
        get :get_course_week_detail
      end
      collection do
        get :get_teacher_search_out
        get :get_teacher_by_name_phone
        get :get_my_students_by_teacher_id
        get :get_my_record_teaching_salary
        get :get_my_students_by_teacher_id
        get :show_my_student_detail
        get :remark_my_student
        get :new_comment_in_teacher
      end
    end

    # 订单
    resources :orders do
    end

    # 公司
    resources :companies do
      collection do
        get :recharge
        get :new_studio
        get :finish_paying
        get :switch_company
      end
    end

    # 员工
    resources :employees do
      collection do
        get 'get_employee'
      end
    end

    # 分店
    resources :studios do
      collection do
        get :finish_paying
        get :switch_studio
        get :update_studio_name
      end
    end

    # 公司设置
    resources :company_configurations do
      collection do
        #删除公司设置
        delete :destroy_configuration
        delete :destroy_goods_category

        #学员设置
        get :student
        post :create_student_group
        post :create_potential_student_group

        #课程设置
        get :course
        post :create_course_room
        post :update_private_education

        #商品设置
        get :goods
        post :create_goods_category

        #人资设置
        get :employee
        post :create_department
        post :create_position
        post :create_teacher_level
        post :create_employee_welfare

        #奖金设置
        get :bonus
        post :update_company_name
        post :update_bonus
      end
    end

  end
end

app/models/good.rb
class Good < ApplicationRecord
  has_many :discounts
  has_many :orders
  belongs_to :company

  def good_status
    if self.stock == 0
      '缺货'
    else
      self.status
    end
  end

  def good_info
    SaleCourse.find(self.good_info_id).name
  end

  def course_unit
    name = self.good_info
    if name == '年卡'
      '年'
    elsif name == '月卡'
      '月'
    elsif name == '次卡'
      '次'
    elsif name == '充值'
      '元'
    else
      '课时'
    end
  end

  def time_discount_price
    percent = self.discounts.where(discount_type: '时间优惠')
                  .where('begin_at <= ? and end_at >= ?', Date.current, Date.current)
                  .minimum(:percent)
    percent = percent || 100
    self.price * percent/100
  end

end

app/controllers/admin/goods_controller.rb
class Admin::GoodsController < ApplicationController
  layout 'studio'
  before_action :set_good, only: [:show, :edit, :update, :destroy, :record, :change_status, :price]
  before_action :authorize_good, except: [:goods_shop]
  before_action :authorize_save, only:[:new,:create]

  def index
    @sale_courses = SaleCourse.where(company_id: nil)
    @sale_courses +=  current_company.sale_courses
    #@goods_categories = current_company.goods_category_configurations

    params[:good_type] ||= "all"
    params[:good_info_id] ||= "all"
    params[:sort] ||= ""

    conditions = ["1=1"]
    conditions << "goods.good_type = '#{params[:good_type]}'" if params[:good_type].present? && params[:good_type] != "all"
    conditions << "goods.good_info_id = '#{params[:good_info_id].to_i}'" if params[:good_info_id].present? && params[:good_info_id] != "all"
    @goods = current_company.goods.where(conditions.join(" and "))
                                  .paginate(page: params[:page], per_page: 5)
                                  .order(params[:sort])
  end

  def get_good_list
    @sale_courses = SaleCourse.where(company_id: nil)
    @sale_courses +=  current_company.sale_courses
    @view_type = params[:view_type]

    params[:good_type] ||= "all"
    params[:good_info_id] ||= "all"
    params[:sort] ||= ""

    conditions = ["1=1"]
    conditions << "goods.good_type = '#{params[:good_type]}'" if params[:good_type].present? && params[:good_type] != "all"
    conditions << "goods.good_info_id = '#{params[:good_info_id].to_i}'" if params[:good_info_id].present? && params[:good_info_id] != "all"
    @goods = current_company.goods.where(conditions.join(" and "))
                                  .paginate(page: params[:page], per_page: 5)
                                  .order(params[:sort])
  end

  def goods_shop

    @sale_courses = SaleCourse.where(company_id: nil)
    @sale_courses +=  current_company.sale_courses

    params[:good_type] ||= "all"
    params[:good_info_id] ||= "all"
    params[:sort] ||= ""

    conditions = ["1=1"]
    conditions << "goods.status = '正常'"
    conditions << "goods.good_type = '#{params[:good_type]}'" if params[:good_type].present? && params[:good_type] != "all"
    conditions << "goods.good_info_id = '#{params[:good_info_id].to_i}'" if params[:good_info_id].present? && params[:good_info_id] != "all"
    @goods = current_company.goods.where(conditions.join(" and "))
                                  .paginate(page: params[:page], per_page: 8)
                                  .order(params[:sort])
  end

  def new

    @others = current_company.sale_courses.where(sale_type: '周边商品')
    @courses = current_company.sale_courses.where(sale_type: '课程商品')
    
    #修改默认的课程商品类型的公司id为0 flydragon
    @courses += SaleCourse.where(company_id: nil,sale_type: '课程商品')
  end

  def create
    p '===========商品============'
    p goods_params
    good = Good.new(goods_params)
    good.company_id = current_company.id
    good.save!

    p '===========折扣============'
    p discount_params
    discount_params.each do |dis|
      discount = Discount.new(dis)
      discount.good_id = good.id
      discount.save!
    end
    respond_to do |format|
      format.js { render js: "window.location.href = '/admin/goods'" }
    end
  end

  def edit
    @sale_courses = SaleCourse.where(company_id: nil)
    @sale_courses +=  current_company.sale_courses
    @discounts = @good.discounts
    @time_discounts = @discounts.where(discount_type: '时间优惠')
    @num_discounts = @discounts.where(discount_type: '数量优惠')
  end

  def update
    p '===========商品============'
    p goods_params
    @good.update!(goods_params)

    p '===========折扣============'
    p discount_params
    discounts = @good.discounts
    discounts.destroy_all

    discount_params.each do |dis|
      discount = Discount.new(dis)
      discount.good_id = @good.id
      discount.save!
    end
    respond_to do |format|
      format.js { render js: "window.location.href = '/admin/goods'" }
    end
  end

  def show
    @discounts = @good.discounts
    @time_discounts = @discounts.where(discount_type: '时间优惠')
    @num_discounts = @discounts.where(discount_type: '数量优惠')

  end

  def change_status
    if @good.status == '正常'
      @good.update!(status: '下架')
    elsif @good.status == '下架'
      @good.update!(status: '正常')
    end
    redirect_to admin_good_path
  end
  

  # 商品交易记录，kevin
  def record
    good_id = params[:id];
    @good = Good.find_by_id(good_id);
    
    @orders_array = Array.new();
    orders = Order.where(good_id: good_id);
    for order in orders
        order_hash = Hash.new();
        order_hash["time"] = DateTime.parse(order.created_at.to_s).strftime('%Y-%m-%d %H:%M').to_s;
        
        if order.student_id != 0
            order_hash["buy_name"] = Student.find_by_id(order.student_id).name;
        else
            # 意向学员和正式学员两种判断
            if PotentialStudent.find_by_id(order.potential_student_id)
                order_hash["buy_name"] = PotentialStudent.find_by_id(order.potential_student_id).name;    
            else
                order_hash["buy_name"] = Student.find_by_potential_student_id(order.potential_student_id).name;    
            end
        end
        

        order_hash["amount"] = order.amount;
        order_hash["total_price"] = order.total_price;

        order_hash["employee_name"] = Employee.find_by_id(order.employee_id).name;      
        if (order_hash["employee_name"].length == 0) || !order_hash["employee_name"]
            order_hash["employee_name"] = "缺少员工信息"  
        end  

        @orders_array.push(order_hash);
    end
    @orders_array = @orders_array.paginate(page: params[:page], per_page: 5);
  end

  def price
    arr = @good.discounts.map { |x| x.discount_percent(params[:unit].to_i) }
    percent = arr.compact.min || 100
    @price = @good.price * percent/100
    @total = @price * (params[:unit].to_i)
  end

  private
  def set_good
    @good = Good.find(params[:id])
  end

  def goods_params
    params.permit(goods: [:good_type, :good_info_id, :name, :amount, :price, :stock, :month_of_validity, :remark, :avatar])[:goods]["0"]
  end

  def discount_params
    params.permit(discount: [:discount_type, :amount, :percent, :begin_at, :end_at] )[:discount].try(:values) || []
  end

  def authorize_good
    authorize Good,:index?
  end

  def authorize_save
    authorize Good,:save?
  end


end

app/views/admin/goods/_good_price.html.erb
<li>
  <span>商品名:</span>
  <em><%= @good.name %></em>
</li>
<li>
  <span>单价:</span>
  <input type="text" name="order[real_price]" id="real_price" value="<%= @price %>">
  <em><%= @price %>元</em>
  <b class="original-cost"><%= @good.price %>元</b>
</li>
<li>
  <span>合计:</span>
   <input type="text" name="order[total_price]" id="total_price" value="<%= @total %>">	
  <em><%= @total %>元</em>
</li>

app/views/admin/goods/_list.html.erb
<div class="comshop-con clearfix">
  <% @goods.each do |good| %>
    <dl>
      <dt>
      <a href="<%= admin_good_path(good) %>">
        <img src="<%= good.avatar_url.present? ? good.avatar_url : '/assets/images/shop-1.jpg' %>" alt="商品">
      </a>
      </dt>
      <dd>
      <h4><%= good.name %></h4>
      <div class="sh-money">
        <span>¥</span>
        <em><%= good.price %></em>
      </div>
      <div class="clearfix">
        <div class="sh-stock">
          <span>库存:</span>
          <em>
            <% if good.stock %>
              <%= good.stock %>
            <% else %>
              -
            <% end %>
          </em>
        </div>
        <div class="sh-sold">
          <span>已售:</span>
          <em><%= good.sale_amount %></em>
        </div>
      </div>
      </dd>
    </dl>
  <% end %>
</div>
<div class="apple_pagination" id="will_page">
  <%= will_paginate @goods, :container => false %>
</div>

app/views/admin/goods/_table.html.erb
<div class="scrollbox">
  <table>
    <thead>
      <tr>
        <th class="commod-name">商品名</th>
        <th class="commod-class">分类</th>
        <th class="commod-type">商品类型</th>
        <th class="commod-stock">库存</th>
        <th class="commod-sale">销量</th>
        <th class="commod-state">状态</th>
        <th class="curl-operation">操作</th>
      </tr>
    </thead>
    <tbody>
      <% @goods.each do |good| %>
        <tr>
          <td><%= good.name %></td>
          <td><%= good.good_type %></td>
          <td><%= good.good_info %></td>
          <td>
            <% if good.stock %>
              <%= good.stock %>
            <% else %>
              -
            <% end %>
          </td>
          <td><%= good.sale_amount %></td>
          <td><%= good.good_status %></td>
          <td class="curl-operation">
            <span>[</span>
            <em><%= link_to '查看详情', admin_good_path(good) %></em>
            <span>]</span>
            <span>[</span>
            <em><%= link_to '交易记录', record_admin_good_path(good) %></em>
            <span>]</span>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="apple_pagination" id="will_page">
    <%= will_paginate @goods, :container => false %>
  </div>
</div>

app/views/admin/goods/get_good_list.js.erb
<% if @view_type == "list" %>
  $(".shop-list").html("<%= j render "list" %>");
  $("#will_page a").attr("data-remote", "true");
<% elsif @view_type == "table" %>
  $(".curlist-con").html("<%= j render "table" %>");
  $("#will_page a").attr("data-remote", "true");
<% end %>

app/views/admin/goods/index.html.erb
<script type="text/javascript" language="javascript" charset="utf-8">
$(".menu-wrap li").removeClass("active-link");
$(".menu-wrap #goods").addClass("active");
$("#goods #info").addClass("active-link");
$("#goods #good_list a").addClass("active-link");
</script>
<div class="common-tit">
  <h2>商品列表</h2>
  <span>商品管理 > 商品列表</span>
  <%= link_to '添加商品', new_admin_good_path, class: "add-staff"%>
</div>
<div class="cur-list">
  <div class="cur-listbox clearfix">
    <div class="cur-ll clearfix">
      <div class="list-box">
        <div class="downbtn">
          <span data_id="all">商品分类</span>
          <em></em>
        </div>
        <ul class="dropdown-menu">
          <li data_id="all">商品分类</li>
          <li data_id="课程商品">课程商品</li>
          <li data_id="周边商品">周边商品</li>
        </ul>
      </div>
      <div class="list-box">
        <div class="downbtn">
          <span data_id="all">商品类型</span>
          <em></em>
        </div>
        <ul class="dropdown-menu">
          <li data_id="all">商品类型</li>
          <% @sale_courses.each do |sale| %>
            <li data_id="<%= sale.id %>"><%= sale.name %></li>
          <% end %>
        </ul>
      </div>
      <div class="list-box">
        <div class="downbtn">
          <span data_id="">排序</span>
          <em></em>
        </div>
        <ul class="dropdown-menu">
          <li data_id="price asc">价格由低到高</li>
          <li data_id="price desc">价格由高到低</li>
          <li data_id="sale_amount asc">销量由低到高</li>
          <li data_id="sale_amount desc">销量由高到低</li>
        </ul>
      </div>
    </div>
  </div>
  <div class="curlist-con">
    <%= render partial: "table" %>
  </div>
</div>
<script src="/assets/js/common.js"></script>
<script>
$(".cur-ll .list-box li").on("click", function() {
  $(this).parent().parent().find("span").attr("data_id", $(this).attr("data_id"));
  transData();
});
function transData() {
  var transD = "";
  transD += "view_type=table&";
  for (var i = 0; i < $(".cur-ll .list-box").length; i++) {
    switch(true) {
      case i == 0: transD += "good_type" + "=" + $($(".cur-ll .list-box")[i]).find("span").attr("data_id") + "&";break;
      case i == 1: transD += "good_info_id" + "=" + $($(".cur-ll .list-box")[i]).find("span").attr("data_id") + "&";break;
      case i == 2: transD += "sort" + "=" + $($(".cur-ll .list-box")[i]).find("span").attr("data_id");break;
    };
  };
  console.log(transD);
  $.ajax({
    type:'get', url:"/admin/goods/get_good_list?"+ transD,
    success: function(data) {
      if (data.error) {
        // console.log("wrong");
      }
    }
  });
};
</script>

app/views/admin/goods/price.js.erb
$("#good_price").html("<%= j render "good_price" %>");

app/views/admin/goods/show.html.erb
<script type="text/javascript" language="javascript" charset="utf-8">
$(".menu-wrap li").removeClass("active-link");
$(".menu-wrap #goods").addClass("active");
$("#goods #info").addClass("active-link");
$("#goods #good_list a").addClass("active-link");
</script>
<div class="mask">
</div>

<div class="common-tit">
  <h2>商品详情</h2>
  <span>商品管理 > 商品详情</span>
  <div class="cours-gbtn">
    <%#<a id="sale" href="javacript:;">售卖</a>%>
    <%=link_to '售卖', new_admin_order_path(good_id: @good.id), remote: true, id: "sale" %>
    <% if @good.status == '下架' %>
      <%=link_to '上架', change_status_admin_good_path(@good), data: {confirm: '确定要下架吗？'} %>
    <% else %>
      <%=link_to '下架', change_status_admin_good_path(@good), data: {confirm: '确定要下架吗？'} %>
    <% end %>
    <%=link_to '编辑', edit_admin_good_path(@good) %>
  </div>
</div>
<div class="course-box">
  <h3>
    <span>基本信息</span>
  </h3>

  <% if @good.good_type == '课程商品' %>
    <div class="commo-dec clearfix">
      <div class="camera">
        <% if @good.avatar.present? %>
          <%= image_tag("#{@good.avatar_url}", size: "150x150", alt: "头像" ,id: "good_avatar_img")%>
        <% else %>
          <%= image_tag("/avatar.png", size: "150x150", alt: "头像" ,id: "good_avatar_img")%>   
        <% end %> 
      </div>
      <ul>
        <li>
          <span>商品分类:</span>
          <em id="comsh"><%= @good.good_type %></em>
        </li>
        <li>
          <span>商品类型:</span>
          <em><%= @good.good_info %></em>
        </li>
        <li>
          <span>商品名称:</span>
          <em><%= @good.name %></em>
        </li>
        <li>
          <span>课程规格:</span>
          <em><%= @good.amount %><%= @good.course_unit %></em>
        </li>
        <li>
          <span>商品价格:</span>
          <em><%= @good.price %></em>
        </li>
        <li>
          <span>商品库存:</span>
          <em>
            <% if @good.stock.present? %>
              <%= @good.stock %>
            <% else %>
              -
            <% end %>
          </em>
        </li>
        <li>
          <span>有效期:</span>
          <em><%= @good.month_of_validity %>月</em>
        </li>
      </ul>
    </div>
  <% elsif @good.good_type == '周边商品' %>
    <div class="commo-dec clearfix">
      <div class="camera">
        <% if @good.avatar.present? %>
          <%= image_tag("#{@good.avatar_url}", size: "150x150", alt: "头像" ,id: "good_avatar_img")%>
        <% else %>
          <%= image_tag("/avatar.png", size: "150x150", alt: "头像" ,id: "good_avatar_img")%>   
        <% end %> 
      </div>
      <ul>
        <li>
          <span>商品分类:</span>
          <em id="comsh"><%= @good.good_type %></em>
        </li>
        <li>
          <span>商品类型:</span>
          <em><%= @good.good_info %></em>
        </li>
        <li>
          <span>商品名称:</span>
          <em><%= @good.name %></em>
        </li>
        <li>
          <span>商品库存:</span>
          <em>
            <% if @good.stock %>
              <%= @good.stock %>
            <% else %>
              -
            <% end %>
          </em>
        </li>
        <li>
          <span>商品价格:</span>
          <em><%= @good.price %></em>
        </li>
        <li class="st-al">
          <span>简介:</span>
          <em>
            <% if @good.remark %>
              <%= @good.remark %>
            <% else %>
              -
            <% end %>
          </em>
        </li>
      </ul>
    </div>
  <% end %>
  <h3>
    <span>相关信息</span>
  </h3>
  <div class="course-b clearfix">
    <div class="relevant clearfix">
      <div>
        <span>销量:</span>
        <em><%= @good.sale_amount %></em>
      </div>
      <div>
        <span>状态:</span>
        <em><%= @good.good_status %></em>
      </div>
    </div>
  </div>
  <% if @discounts.present? %>
    <h3>
      <span>折扣优惠</span>
    </h3>
    <div class="course-b clearfix">
      <div class="co-discount clearfix">
        <% if @num_discounts.present? %>
          <div class="showdis">
            <span>数量:</span>
          </div>
          <div class="showdis-con">
            <% @num_discounts.each do |num| %>
             <div>
              <span>超过</span>
              <em><%= num.amount %></em>
              <b>件</b>
              <strong>折扣为:</strong>
              <em><%= num.percent %></em>
              <b>%</b>
            </div>
            <% end %>
          </div>
        <% end %>
        <% if @time_discounts.present? %>
          <div class="showdis">
            <span>时间:</span>
          </div>
          <div class="showdis-con">
            <% @time_discounts.each do |time| %>
              <div>
              <em><%= time.begin_at.strftime("%Y年%m月%d日") %></em>
              <i>-</i>
              <em><%= time.end_at.strftime("%Y年%m月%d日") %></em>
              <strong>折扣为:</strong>
              <em><%= time.percent %></em>
              <b>%</b>
              </div>
            <% end %>
          </div>
        <% end %>

      </div>
    </div>
  <% end %>
</div>
</div>
<script src="/assets/js/common.js"></script>
<script>
if ($("#comsh").text() == "课程商品") {
  $(".c-nost").css({
    "display" : "none"
  })
};
$(".purch-num").change(function() {
  console.log($(this).val());
  var unit = $(this).val();
    $.ajax({
      type:'get', url:"/admin/goods/" + <%= @good.id %> + "/price?unit=" + unit,
      success: function(data) {
        if (data.error) {
        }
      }
    });
})
// 控制radio按钮
$(".purch-b .ra-btn").on("click", function() {
  $(this).prev().attr("checked", "checked");
})
// 可放 common.js
$(".mask .ra-btn").on("click", function() {
  $(".mask .ra-btn").removeClass("ra-checked");
  $(this).addClass("ra-checked");
  $(this).prev("input").prop("checked", true);
  if ($(this).hasClass("no-st")) {
    $("#cho-stud").css({
      "display" : "none"
    });
  } else {
    $("#cho-stud").css({
      "display" : "block"
    });
    if ($(this).hasClass("dis-s")) {
      $("#cho-stud .intention").css({
        "display" : "none"
      });
      $("#cho-stud .n-intention").css({
        "display" : "block"
      });
    } else {
      $("#cho-stud .intention").css({
        "display" : "block"
      });
      $("#cho-stud .n-intention").css({
        "display" : "none"
      });
    }
  }
});
$("#sale").on("click", function() {
  $(".mask").css({
    "display" : "block"
  });
  $(".mask-box").css({
    "margin-top" : -($(".mask-box").height() + parseInt($(".mask-box").css("padding-bottom")))/2
  })
})
// 弹窗(有重复则删除)
$(".mask-head span").on("click", function() {
  $(this).parent().parent().find("input").val("");
  $(".mask").css({
    "display" : "none"
  })
})
$(".mask-confirm").on("click", function() {
  $(".mask").css({
    "display" : "none"
  })
})
/* 单选下拉列表 */
$(".purch-b .single-downbtn").on("click", function() {
  if ($(this).next(".single-dropdown").hasClass("menuopen")) {
    $(this).next(".single-dropdown").removeClass("menuopen");
  } else {
    $(this).next(".single-dropdown").addClass("menuopen");
    $(this).parent().hover(function() {

    }, function() {
      $(this).children(".single-dropdown").removeClass("menuopen");
    });
    $(".purch-b .menuopen li").on("click", function() {
      $(this).parent().parent().removeClass("menuopen");
      $(this).parent().parent().parent().find("span").text($(this).text());
      $(this).parent().parent().find("input").val("");
      $(".purch-b .single-dropdown li").removeClass("mul-hide");
      $("#choStu").val($(this).attr("data_id"));
    });
    $(this).next("div").find("input").on('input',function(){
      console.log($(this));
      if ($(this).val() != "") {
          console.log($(this).val());
          $(".purch-b .single-dropdown li").addClass("mul-hide");
          console.log($($(".single-dropdown li:contains(" + $(this).val() + ")")).removeClass("mul-hide"));
      } else {
        $(".purch-b .single-dropdown li").removeClass("mul-hide");
      }
    })
  }
});
</script>